// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: video/video.proto

package videopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "onepark/proto/common"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_video_video_proto protoreflect.FileDescriptor

const file_video_video_proto_rawDesc = "" +
	"\n" +
	"\x11video/video.proto\x12\ronepark.video\x1a\x13common/common.proto2D\n" +
	"\fVideoService\x124\n" +
	"\x04Ping\x12\x15.onepark.common.Empty\x1a\x15.onepark.common.EmptyB\x1dZ\x1bonepark/proto/video;videopbb\x06proto3"

var file_video_video_proto_goTypes = []any{
	(*common.Empty)(nil), // 0: onepark.common.Empty
}
var file_video_video_proto_depIdxs = []int32{
	0, // 0: onepark.video.VideoService.Ping:input_type -> onepark.common.Empty
	0, // 1: onepark.video.VideoService.Ping:output_type -> onepark.common.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_video_proto_init() }
func file_video_video_proto_init() {
	if File_video_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_video_proto_rawDesc), len(file_video_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_video_proto_goTypes,
		DependencyIndexes: file_video_video_proto_depIdxs,
	}.Build()
	File_video_video_proto = out.File
	file_video_video_proto_goTypes = nil
	file_video_video_proto_depIdxs = nil
}
