// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: workorder/workorder.proto

package workorderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "onepark/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	WorkorderService_Ping_FullMethodName           = "/onepark.workorder.WorkorderService/Ping"
	WorkorderService_ListWorkOrders_FullMethodName = "/onepark.workorder.WorkorderService/ListWorkOrders"
)

// WorkorderServiceClient is the client API for WorkorderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkorderServiceClient interface {
	// Ping 探活
	Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
	// ListWorkOrders 供 M5 运营调度大屏聚合查询工单(支持按状态/园区过滤与分页)
	// 返回工单摘要列表、总数以及"待处理(待派单+处理中)工单数"
	ListWorkOrders(ctx context.Context, in *ListWorkOrdersReq, opts ...grpc.CallOption) (*ListWorkOrdersResp, error)
}

type workorderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkorderServiceClient(cc grpc.ClientConnInterface) WorkorderServiceClient {
	return &workorderServiceClient{cc}
}

func (c *workorderServiceClient) Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, WorkorderService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workorderServiceClient) ListWorkOrders(ctx context.Context, in *ListWorkOrdersReq, opts ...grpc.CallOption) (*ListWorkOrdersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkOrdersResp)
	err := c.cc.Invoke(ctx, WorkorderService_ListWorkOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkorderServiceServer is the server API for WorkorderService service.
// All implementations must embed UnimplementedWorkorderServiceServer
// for forward compatibility
type WorkorderServiceServer interface {
	// Ping 探活
	Ping(context.Context, *common.Empty) (*common.Empty, error)
	// ListWorkOrders 供 M5 运营调度大屏聚合查询工单(支持按状态/园区过滤与分页)
	// 返回工单摘要列表、总数以及"待处理(待派单+处理中)工单数"
	ListWorkOrders(context.Context, *ListWorkOrdersReq) (*ListWorkOrdersResp, error)
	mustEmbedUnimplementedWorkorderServiceServer()
}

// UnimplementedWorkorderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWorkorderServiceServer struct {
}

func (UnimplementedWorkorderServiceServer) Ping(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWorkorderServiceServer) ListWorkOrders(context.Context, *ListWorkOrdersReq) (*ListWorkOrdersResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWorkOrders not implemented")
}
func (UnimplementedWorkorderServiceServer) mustEmbedUnimplementedWorkorderServiceServer() {}

// UnsafeWorkorderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkorderServiceServer will
// result in compilation errors.
type UnsafeWorkorderServiceServer interface {
	mustEmbedUnimplementedWorkorderServiceServer()
}

func RegisterWorkorderServiceServer(s grpc.ServiceRegistrar, srv WorkorderServiceServer) {
	s.RegisterService(&WorkorderService_ServiceDesc, srv)
}

func _WorkorderService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkorderServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkorderService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkorderServiceServer).Ping(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkorderService_ListWorkOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkOrdersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkorderServiceServer).ListWorkOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkorderService_ListWorkOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkorderServiceServer).ListWorkOrders(ctx, req.(*ListWorkOrdersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkorderService_ServiceDesc is the grpc.ServiceDesc for WorkorderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkorderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepark.workorder.WorkorderService",
	HandlerType: (*WorkorderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _WorkorderService_Ping_Handler,
		},
		{
			MethodName: "ListWorkOrders",
			Handler:    _WorkorderService_ListWorkOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workorder/workorder.proto",
}
