// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: workorder/workorder.proto

package workorderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "onepark/proto/common"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_workorder_workorder_proto protoreflect.FileDescriptor

const file_workorder_workorder_proto_rawDesc = "" +
	"\n" +
	"\x19workorder/workorder.proto\x12\x11onepark.workorder\x1a\x13common/common.proto2H\n" +
	"\x10WorkorderService\x124\n" +
	"\x04Ping\x12\x15.onepark.common.Empty\x1a\x15.onepark.common.EmptyB%Z#onepark/proto/workorder;workorderpbb\x06proto3"

var file_workorder_workorder_proto_goTypes = []any{
	(*common.Empty)(nil), // 0: onepark.common.Empty
}
var file_workorder_workorder_proto_depIdxs = []int32{
	0, // 0: onepark.workorder.WorkorderService.Ping:input_type -> onepark.common.Empty
	0, // 1: onepark.workorder.WorkorderService.Ping:output_type -> onepark.common.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workorder_workorder_proto_init() }
func file_workorder_workorder_proto_init() {
	if File_workorder_workorder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workorder_workorder_proto_rawDesc), len(file_workorder_workorder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workorder_workorder_proto_goTypes,
		DependencyIndexes: file_workorder_workorder_proto_depIdxs,
	}.Build()
	File_workorder_workorder_proto = out.File
	file_workorder_workorder_proto_goTypes = nil
	file_workorder_workorder_proto_depIdxs = nil
}
