// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: workorder/workorder.proto

package workorderpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "onepark/proto/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListWorkOrdersReq 工单列表查询请求
type ListWorkOrdersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TenantId int64 `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 园区ID(RBAC 隔离), 0 表示不限
	Status   int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                     // 状态过滤: 0不限, 其它见 work_order.status 取值
	Page     int64 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 页码(从1开始)
	PageSize int64 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页大小
}

func (x *ListWorkOrdersReq) Reset() {
	*x = ListWorkOrdersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_workorder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkOrdersReq) ProtoMessage() {}

func (x *ListWorkOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_workorder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkOrdersReq.ProtoReflect.Descriptor instead.
func (*ListWorkOrdersReq) Descriptor() ([]byte, []int) {
	return file_workorder_workorder_proto_rawDescGZIP(), []int{0}
}

func (x *ListWorkOrdersReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *ListWorkOrdersReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListWorkOrdersReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWorkOrdersReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// WorkOrderSummary 工单摘要(大屏展示用, 避免传输大字段)
type WorkOrderSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                   // 工单ID
	OrderNo    string `protobuf:"bytes,2,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`           // 工单号
	Type       int32  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                               // 工单类型
	Status     int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                           // 当前状态
	Priority   int32  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                       // 优先级
	AssigneeId int64  `protobuf:"varint,6,opt,name=assignee_id,json=assigneeId,proto3" json:"assignee_id,omitempty"` // 处理人
	CreatedAt  int64  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // 创建时间(秒级时间戳)
}

func (x *WorkOrderSummary) Reset() {
	*x = WorkOrderSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_workorder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkOrderSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkOrderSummary) ProtoMessage() {}

func (x *WorkOrderSummary) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_workorder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkOrderSummary.ProtoReflect.Descriptor instead.
func (*WorkOrderSummary) Descriptor() ([]byte, []int) {
	return file_workorder_workorder_proto_rawDescGZIP(), []int{1}
}

func (x *WorkOrderSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkOrderSummary) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *WorkOrderSummary) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *WorkOrderSummary) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WorkOrderSummary) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *WorkOrderSummary) GetAssigneeId() int64 {
	if x != nil {
		return x.AssigneeId
	}
	return 0
}

func (x *WorkOrderSummary) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// ListWorkOrdersResp 工单列表响应
type ListWorkOrdersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total        int64               `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                                   // 符合条件总数
	List         []*WorkOrderSummary `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`                                      // 当前页数据
	PendingCount int64               `protobuf:"varint,3,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"` // 待处理(待派单+处理中)工单总数
}

func (x *ListWorkOrdersResp) Reset() {
	*x = ListWorkOrdersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_workorder_workorder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWorkOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkOrdersResp) ProtoMessage() {}

func (x *ListWorkOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_workorder_workorder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkOrdersResp.ProtoReflect.Descriptor instead.
func (*ListWorkOrdersResp) Descriptor() ([]byte, []int) {
	return file_workorder_workorder_proto_rawDescGZIP(), []int{2}
}

func (x *ListWorkOrdersResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWorkOrdersResp) GetList() []*WorkOrderSummary {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListWorkOrdersResp) GetPendingCount() int64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

var File_workorder_workorder_proto protoreflect.FileDescriptor

var file_workorder_workorder_proto_rawDesc = []byte{
	0x0a, 0x19, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x77, 0x6f, 0x72, 0x6b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x6f, 0x6e, 0x65,
	0x70, 0x61, 0x72, 0x6b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x13,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x79, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xc5,
	0x01, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x6f, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x61, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x37, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x32, 0xa7, 0x01, 0x0a, 0x10, 0x57, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15,
	0x2e, 0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x5d, 0x0a, 0x0e,
	0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x24,
	0x2e, 0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x77,
	0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72,
	0x6b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x25, 0x5a, 0x23, 0x6f,
	0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x77, 0x6f, 0x72,
	0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x3b, 0x77, 0x6f, 0x72, 0x6b, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_workorder_workorder_proto_rawDescOnce sync.Once
	file_workorder_workorder_proto_rawDescData = file_workorder_workorder_proto_rawDesc
)

func file_workorder_workorder_proto_rawDescGZIP() []byte {
	file_workorder_workorder_proto_rawDescOnce.Do(func() {
		file_workorder_workorder_proto_rawDescData = protoimpl.X.CompressGZIP(file_workorder_workorder_proto_rawDescData)
	})
	return file_workorder_workorder_proto_rawDescData
}

var file_workorder_workorder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workorder_workorder_proto_goTypes = []any{
	(*ListWorkOrdersReq)(nil),  // 0: onepark.workorder.ListWorkOrdersReq
	(*WorkOrderSummary)(nil),   // 1: onepark.workorder.WorkOrderSummary
	(*ListWorkOrdersResp)(nil), // 2: onepark.workorder.ListWorkOrdersResp
	(*common.Empty)(nil),       // 3: onepark.common.Empty
}
var file_workorder_workorder_proto_depIdxs = []int32{
	1, // 0: onepark.workorder.ListWorkOrdersResp.list:type_name -> onepark.workorder.WorkOrderSummary
	3, // 1: onepark.workorder.WorkorderService.Ping:input_type -> onepark.common.Empty
	0, // 2: onepark.workorder.WorkorderService.ListWorkOrders:input_type -> onepark.workorder.ListWorkOrdersReq
	3, // 3: onepark.workorder.WorkorderService.Ping:output_type -> onepark.common.Empty
	2, // 4: onepark.workorder.WorkorderService.ListWorkOrders:output_type -> onepark.workorder.ListWorkOrdersResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_workorder_workorder_proto_init() }
func file_workorder_workorder_proto_init() {
	if File_workorder_workorder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_workorder_workorder_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ListWorkOrdersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_workorder_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WorkOrderSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_workorder_workorder_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListWorkOrdersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_workorder_workorder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workorder_workorder_proto_goTypes,
		DependencyIndexes: file_workorder_workorder_proto_depIdxs,
		MessageInfos:      file_workorder_workorder_proto_msgTypes,
	}.Build()
	File_workorder_workorder_proto = out.File
	file_workorder_workorder_proto_rawDesc = nil
	file_workorder_workorder_proto_goTypes = nil
	file_workorder_workorder_proto_depIdxs = nil
}
