// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/user-manage/internal/svc"
	"onepark/common/health"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{Method: http.MethodPost, Path: "/api/users", Handler: UserCreateHandler(serverCtx)},
			{Method: http.MethodPut, Path: "/api/users", Handler: UserUpdateHandler(serverCtx)},
			{Method: http.MethodDelete, Path: "/api/users/:id", Handler: UserDeleteHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/api/users/:id", Handler: UserDetailHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/api/users", Handler: UserListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/api/roles", Handler: RoleCreateHandler(serverCtx)},
			{Method: http.MethodGet, Path: "/api/roles", Handler: RoleListHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/api/users/roles", Handler: RoleAssignHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/api/menus", Handler: MenuCreateHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/api/roles/menus", Handler: RoleMenuAssignHandler(serverCtx)},
			{Method: http.MethodPost, Path: "/api/permissions/check", Handler: PermissionCheckHandler(serverCtx)},
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.Handler(serverCtx.DB, nil),
			},
		},
	)
}
