// Code generated by goctl. DO NOT EDIT.
//
// 本文件声明 workorder-service 的全部 HTTP 路由并注册到 go-zero rest.Server.
// 注意: 这里的 Path 是"服务内网直连路径"; 对外统一经根目录 gateway(8080) 以 /api/workorder 前缀转发.
package handler

import (
	"net/http"

	"onepark/app/workorder-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 把本服务的 HTTP 路由挂载到 go-zero HTTP 服务器.
// 入参 server: go-zero 服务器实例; serverCtx: 全局依赖(DB/Redis/Kafka 生产者等), 注入到各 handler.
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建工单(建单即待派单)
				Method:  http.MethodPost,
				Path:    "/api/workorder",
				Handler: CreateWorkOrderHandler(serverCtx),
			},
			{
				// 工单详情
				Method:  http.MethodGet,
				Path:    "/api/workorder/:id",
				Handler: GetWorkOrderHandler(serverCtx),
			},
			{
				// 派单(待派单→处理中, FSM+乐观锁)
				Method:  http.MethodPut,
				Path:    "/api/workorder/:id/assign",
				Handler: AssignWorkOrderHandler(serverCtx),
			},
			{
				// 状态流转(submit/approve/reject/close)
				Method:  http.MethodPut,
				Path:    "/api/workorder/:id/status",
				Handler: UpdateWorkOrderStatusHandler(serverCtx),
			},
			{
				// 工单分页列表
				Method:  http.MethodGet,
				Path:    "/api/workorders",
				Handler: ListWorkOrdersHandler(serverCtx),
			},
		},
	)
}
