// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/workorder-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/workorder",
				Handler: CreateWorkOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/workorder/:id",
				Handler: GetWorkOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/workorder/:id/assign",
				Handler: AssignWorkOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/workorder/:id/status",
				Handler: UpdateWorkOrderStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/workorders",
				Handler: ListWorkOrdersHandler(serverCtx),
			},
		},
	)
}
