// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: energy/energy.proto

package energypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "onepark/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EnergyDataService_Ping_FullMethodName = "/onepark.energy.EnergyDataService/Ping"
)

// EnergyDataServiceClient is the client API for EnergyDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnergyDataServiceClient interface {
	// TODO: 业务接口由各服务负责人按 OpenViking 记忆中的接口清单补充
	Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
}

type energyDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnergyDataServiceClient(cc grpc.ClientConnInterface) EnergyDataServiceClient {
	return &energyDataServiceClient{cc}
}

func (c *energyDataServiceClient) Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, EnergyDataService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnergyDataServiceServer is the server API for EnergyDataService service.
// All implementations must embed UnimplementedEnergyDataServiceServer
// for forward compatibility
type EnergyDataServiceServer interface {
	// TODO: 业务接口由各服务负责人按 OpenViking 记忆中的接口清单补充
	Ping(context.Context, *common.Empty) (*common.Empty, error)
	mustEmbedUnimplementedEnergyDataServiceServer()
}

// UnimplementedEnergyDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEnergyDataServiceServer struct {
}

func (UnimplementedEnergyDataServiceServer) Ping(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEnergyDataServiceServer) mustEmbedUnimplementedEnergyDataServiceServer() {}

// UnsafeEnergyDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnergyDataServiceServer will
// result in compilation errors.
type UnsafeEnergyDataServiceServer interface {
	mustEmbedUnimplementedEnergyDataServiceServer()
}

func RegisterEnergyDataServiceServer(s grpc.ServiceRegistrar, srv EnergyDataServiceServer) {
	s.RegisterService(&EnergyDataService_ServiceDesc, srv)
}

func _EnergyDataService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnergyDataServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnergyDataService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnergyDataServiceServer).Ping(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EnergyDataService_ServiceDesc is the grpc.ServiceDesc for EnergyDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnergyDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepark.energy.EnergyDataService",
	HandlerType: (*EnergyDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _EnergyDataService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "energy/energy.proto",
}
