// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: energy/energy.proto

package energypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "onepark/proto/common"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDailyReportRequest 当日能耗查询条件
type GetDailyReportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// date 统计哪一天, 格式 2026-09-15; 空表示今天
	Date string `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	// zone_id 只看某个区域, 如 A栋; 空表示全园区
	ZoneId string `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
}

func (x *GetDailyReportRequest) Reset() {
	*x = GetDailyReportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_energy_energy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDailyReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReportRequest) ProtoMessage() {}

func (x *GetDailyReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_energy_energy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReportRequest.ProtoReflect.Descriptor instead.
func (*GetDailyReportRequest) Descriptor() ([]byte, []int) {
	return file_energy_energy_proto_rawDescGZIP(), []int{0}
}

func (x *GetDailyReportRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDailyReportRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

// GetDailyReportResponse 当日能耗汇总
type GetDailyReportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Date          string  `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`                                            // 统计日期, 如 2026-09-15
	ZoneId        string  `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`                          // 区域, 空表示全园区
	TotalUsageKwh float64 `protobuf:"fixed64,3,opt,name=total_usage_kwh,json=totalUsageKwh,proto3" json:"total_usage_kwh,omitempty"` // 当日总用量(度) = 各设备(期末读数-期初读数)求和
	UpdatedAt     string  `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`                 // 最新一条数据的采集时间
}

func (x *GetDailyReportResponse) Reset() {
	*x = GetDailyReportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_energy_energy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDailyReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDailyReportResponse) ProtoMessage() {}

func (x *GetDailyReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_energy_energy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDailyReportResponse.ProtoReflect.Descriptor instead.
func (*GetDailyReportResponse) Descriptor() ([]byte, []int) {
	return file_energy_energy_proto_rawDescGZIP(), []int{1}
}

func (x *GetDailyReportResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDailyReportResponse) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *GetDailyReportResponse) GetTotalUsageKwh() float64 {
	if x != nil {
		return x.TotalUsageKwh
	}
	return 0
}

func (x *GetDailyReportResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_energy_energy_proto protoreflect.FileDescriptor

var file_energy_energy_proto_rawDesc = []byte{
	0x0a, 0x13, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2f, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64,
	0x22, 0x8c, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x7a, 0x6f, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x7a, 0x6f, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x6b, 0x77, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0d, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x73, 0x61, 0x67, 0x65, 0x4b, 0x77, 0x68,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32,
	0xaa, 0x01, 0x0a, 0x11, 0x45, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x44, 0x61, 0x74, 0x61, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e,
	0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x15, 0x2e, 0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x5f, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x2e,
	0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x47,
	0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2e, 0x65,
	0x6e, 0x65, 0x72, 0x67, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d,
	0x6f, 0x6e, 0x65, 0x70, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65, 0x6e,
	0x65, 0x72, 0x67, 0x79, 0x3b, 0x65, 0x6e, 0x65, 0x72, 0x67, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_energy_energy_proto_rawDescOnce sync.Once
	file_energy_energy_proto_rawDescData = file_energy_energy_proto_rawDesc
)

func file_energy_energy_proto_rawDescGZIP() []byte {
	file_energy_energy_proto_rawDescOnce.Do(func() {
		file_energy_energy_proto_rawDescData = protoimpl.X.CompressGZIP(file_energy_energy_proto_rawDescData)
	})
	return file_energy_energy_proto_rawDescData
}

var file_energy_energy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_energy_energy_proto_goTypes = []any{
	(*GetDailyReportRequest)(nil),  // 0: onepark.energy.GetDailyReportRequest
	(*GetDailyReportResponse)(nil), // 1: onepark.energy.GetDailyReportResponse
	(*common.Empty)(nil),           // 2: onepark.common.Empty
}
var file_energy_energy_proto_depIdxs = []int32{
	2, // 0: onepark.energy.EnergyDataService.Ping:input_type -> onepark.common.Empty
	0, // 1: onepark.energy.EnergyDataService.GetDailyReport:input_type -> onepark.energy.GetDailyReportRequest
	2, // 2: onepark.energy.EnergyDataService.Ping:output_type -> onepark.common.Empty
	1, // 3: onepark.energy.EnergyDataService.GetDailyReport:output_type -> onepark.energy.GetDailyReportResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_energy_energy_proto_init() }
func file_energy_energy_proto_init() {
	if File_energy_energy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_energy_energy_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetDailyReportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_energy_energy_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetDailyReportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_energy_energy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_energy_energy_proto_goTypes,
		DependencyIndexes: file_energy_energy_proto_depIdxs,
		MessageInfos:      file_energy_energy_proto_msgTypes,
	}.Build()
	File_energy_energy_proto = out.File
	file_energy_energy_proto_rawDesc = nil
	file_energy_energy_proto_goTypes = nil
	file_energy_energy_proto_depIdxs = nil
}
