// Code generated by goctl. DO NOT EDIT.
package types

// Location 摄像头位置(docs/m3/04 #49)
type Location struct {
	Lng   float64 `json:"lng"`
	Lat   float64 `json:"lat"`
	Floor string  `json:"floor,optional"`
}

// AddCameraReq 添加摄像头请求(#49)
type AddCameraReq struct {
	Name     string    `json:"name"`
	DeviceId string    `json:"device_id"`
	AreaId   int64     `json:"area_id,optional"`
	RtspUrl  string    `json:"rtsp_url"`
	Location *Location `json:"location,optional"`
	Status   int8      `json:"status,optional"`
}

// AddCameraResp 添加摄像头响应
type AddCameraResp struct {
	Id int64 `json:"id"`
}

// CameraItem 摄像头列表项(#50)
type CameraItem struct {
	Id              int64  `json:"id"`
	Name            string `json:"name"`
	DeviceId        string `json:"device_id"`
	AreaId          int64  `json:"area_id"`
	Status          int8   `json:"status"`
	LastHeartbeatAt int64  `json:"last_heartbeat_at"`
	CreatedAt       int64  `json:"created_at"`
}

// ListCamerasReq 摄像头列表请求
type ListCamerasReq struct {
	AreaId   int64 `form:"area_id,optional"`
	Status   int8  `form:"status,optional"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

// ListCamerasResp 摄像头分页列表响应
type ListCamerasResp struct {
	Total    int64        `json:"total"`
	Page     int64        `json:"page"`
	PageSize int64        `json:"page_size"`
	List     []CameraItem `json:"list"`
}

// IdReq 按ID查询请求
type IdReq struct {
	Id int64 `path:"id"`
}

// StreamResp 视频流地址响应(#51)
type StreamResp struct {
	CameraId  int64  `json:"camera_id"`
	RtspUrl   string `json:"rtsp_url"`
	FlvUrl    string `json:"flv_url"`
	ExpiresAt int64  `json:"expires_at"`
}
