// Code generated by goctl. DO NOT EDIT.
package types

type ActiveParkingReq struct {
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type ListParkingReq struct {
	Status   int8   `form:"status,optional"`
	PlateNo  string `form:"plate_no,optional"`
	Page     int64  `form:"page"`
	PageSize int64  `form:"page_size"`
}

type ParkingEntryReq struct {
	PlateNo     string `json:"plate_no"`     // 车牌号
	VehicleType int8   `json:"vehicle_type"` // 1月卡 2临时 3VIP 4异常
	DeviceIDIn  string `json:"device_id_in"` // 入场设备(地磁)ID
}

type ParkingExitReq struct {
	PlateNo     string `json:"plate_no"`
	DeviceIDOut string `json:"device_id_out"` // 出场设备(地磁)ID
}

type ParkingItem struct {
	Id        int64  `json:"id"`
	PlateNo   string `json:"plate_no"`
	EntryTime int64  `json:"entry_time"`
	ExitTime  int64  `json:"exit_time,optional"`
	Status    int8   `json:"status"`
	Fee       string `json:"fee,optional"`
}

type ParkingListResp struct {
	Total int64         `json:"total"`
	List  []ParkingItem `json:"list"`
}

type ParkingRecordResp struct {
	Id          int64  `json:"id"`
	PlateNo     string `json:"plate_no"`
	EntryTime   int64  `json:"entry_time"` // 入场时间(秒级时间戳)
	ExitTime    int64  `json:"exit_time,optional"`
	DurationMin int64  `json:"duration_min,optional"` // 停车时长(分钟)
	Fee         string `json:"fee,optional"`          // 停车费(decimal 字符串, 避免浮点误差)
	Status      int8   `json:"status"`                // 1停车中 2已完成
}
