// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: leasing/leasing.proto

package leasingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "onepark/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	LeasingService_Ping_FullMethodName = "/onepark.leasing.LeasingService/Ping"
)

// LeasingServiceClient is the client API for LeasingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeasingServiceClient interface {
	// TODO: 业务接口由各服务负责人按 OpenViking 记忆中的接口清单补充
	Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
}

type leasingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeasingServiceClient(cc grpc.ClientConnInterface) LeasingServiceClient {
	return &leasingServiceClient{cc}
}

func (c *leasingServiceClient) Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, LeasingService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeasingServiceServer is the server API for LeasingService service.
// All implementations must embed UnimplementedLeasingServiceServer
// for forward compatibility
type LeasingServiceServer interface {
	// TODO: 业务接口由各服务负责人按 OpenViking 记忆中的接口清单补充
	Ping(context.Context, *common.Empty) (*common.Empty, error)
	mustEmbedUnimplementedLeasingServiceServer()
}

// UnimplementedLeasingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLeasingServiceServer struct {
}

func (UnimplementedLeasingServiceServer) Ping(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLeasingServiceServer) mustEmbedUnimplementedLeasingServiceServer() {}

// UnsafeLeasingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeasingServiceServer will
// result in compilation errors.
type UnsafeLeasingServiceServer interface {
	mustEmbedUnimplementedLeasingServiceServer()
}

func RegisterLeasingServiceServer(s grpc.ServiceRegistrar, srv LeasingServiceServer) {
	s.RegisterService(&LeasingService_ServiceDesc, srv)
}

func _LeasingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeasingService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasingServiceServer).Ping(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// LeasingService_ServiceDesc is the grpc.ServiceDesc for LeasingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeasingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepark.leasing.LeasingService",
	HandlerType: (*LeasingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LeasingService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leasing/leasing.proto",
}
