// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: leasing/leasing.proto

package leasingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "onepark/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LeasingService_Ping_FullMethodName         = "/onepark.leasing.LeasingService/Ping"
	LeasingService_GetContract_FullMethodName  = "/onepark.leasing.LeasingService/GetContract"
	LeasingService_GetOccupancy_FullMethodName = "/onepark.leasing.LeasingService/GetOccupancy"
)

// LeasingServiceClient is the client API for LeasingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeasingServiceClient interface {
	Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
	// GetContract 按合同ID查询合同主信息
	// (组长一周开发任务计划 周六「leasing-service gRPC 业务接口补充」)。
	// 返回字段与 HTTP GET /api/lease/contract/:id 完全一致(同一 logic 实现)。
	GetContract(ctx context.Context, in *GetContractReq, opts ...grpc.CallOption) (*GetContractResp, error)
	// GetOccupancy 查询园区入驻率 = 已租面积 / 可租总面积
	// (组长一周开发任务计划 周六)。与 HTTP GET /api/lease/occupancy 同一实现。
	GetOccupancy(ctx context.Context, in *GetOccupancyReq, opts ...grpc.CallOption) (*GetOccupancyResp, error)
}

type leasingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeasingServiceClient(cc grpc.ClientConnInterface) LeasingServiceClient {
	return &leasingServiceClient{cc}
}

func (c *leasingServiceClient) Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, LeasingService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leasingServiceClient) GetContract(ctx context.Context, in *GetContractReq, opts ...grpc.CallOption) (*GetContractResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContractResp)
	err := c.cc.Invoke(ctx, LeasingService_GetContract_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leasingServiceClient) GetOccupancy(ctx context.Context, in *GetOccupancyReq, opts ...grpc.CallOption) (*GetOccupancyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOccupancyResp)
	err := c.cc.Invoke(ctx, LeasingService_GetOccupancy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeasingServiceServer is the server API for LeasingService service.
// All implementations must embed UnimplementedLeasingServiceServer
// for forward compatibility.
type LeasingServiceServer interface {
	Ping(context.Context, *common.Empty) (*common.Empty, error)
	// GetContract 按合同ID查询合同主信息
	// (组长一周开发任务计划 周六「leasing-service gRPC 业务接口补充」)。
	// 返回字段与 HTTP GET /api/lease/contract/:id 完全一致(同一 logic 实现)。
	GetContract(context.Context, *GetContractReq) (*GetContractResp, error)
	// GetOccupancy 查询园区入驻率 = 已租面积 / 可租总面积
	// (组长一周开发任务计划 周六)。与 HTTP GET /api/lease/occupancy 同一实现。
	GetOccupancy(context.Context, *GetOccupancyReq) (*GetOccupancyResp, error)
	mustEmbedUnimplementedLeasingServiceServer()
}

// UnimplementedLeasingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLeasingServiceServer struct{}

func (UnimplementedLeasingServiceServer) Ping(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLeasingServiceServer) GetContract(context.Context, *GetContractReq) (*GetContractResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContract not implemented")
}
func (UnimplementedLeasingServiceServer) GetOccupancy(context.Context, *GetOccupancyReq) (*GetOccupancyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOccupancy not implemented")
}
func (UnimplementedLeasingServiceServer) mustEmbedUnimplementedLeasingServiceServer() {}
func (UnimplementedLeasingServiceServer) testEmbeddedByValue()                        {}

// UnsafeLeasingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeasingServiceServer will
// result in compilation errors.
type UnsafeLeasingServiceServer interface {
	mustEmbedUnimplementedLeasingServiceServer()
}

func RegisterLeasingServiceServer(s grpc.ServiceRegistrar, srv LeasingServiceServer) {
	// If the following call panics, it indicates UnimplementedLeasingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LeasingService_ServiceDesc, srv)
}

func _LeasingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeasingService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasingServiceServer).Ping(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeasingService_GetContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContractReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasingServiceServer).GetContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeasingService_GetContract_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasingServiceServer).GetContract(ctx, req.(*GetContractReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeasingService_GetOccupancy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOccupancyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeasingServiceServer).GetOccupancy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeasingService_GetOccupancy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeasingServiceServer).GetOccupancy(ctx, req.(*GetOccupancyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// LeasingService_ServiceDesc is the grpc.ServiceDesc for LeasingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeasingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepark.leasing.LeasingService",
	HandlerType: (*LeasingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LeasingService_Ping_Handler,
		},
		{
			MethodName: "GetContract",
			Handler:    _LeasingService_GetContract_Handler,
		},
		{
			MethodName: "GetOccupancy",
			Handler:    _LeasingService_GetOccupancy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leasing/leasing.proto",
}
