// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: leasing/leasing.proto

package leasingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "onepark/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetContractReq 合同查询请求
type GetContractReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                             // 合同ID
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 园区ID(RBAC 数据隔离); 0 表示不校验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractReq) Reset() {
	*x = GetContractReq{}
	mi := &file_leasing_leasing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractReq) ProtoMessage() {}

func (x *GetContractReq) ProtoReflect() protoreflect.Message {
	mi := &file_leasing_leasing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractReq.ProtoReflect.Descriptor instead.
func (*GetContractReq) Descriptor() ([]byte, []int) {
	return file_leasing_leasing_proto_rawDescGZIP(), []int{0}
}

func (x *GetContractReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetContractReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type GetContractResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *Contract              `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractResp) Reset() {
	*x = GetContractResp{}
	mi := &file_leasing_leasing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractResp) ProtoMessage() {}

func (x *GetContractResp) ProtoReflect() protoreflect.Message {
	mi := &file_leasing_leasing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractResp.ProtoReflect.Descriptor instead.
func (*GetContractResp) Descriptor() ([]byte, []int) {
	return file_leasing_leasing_proto_rawDescGZIP(), []int{1}
}

func (x *GetContractResp) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

// Contract 合同主信息。
// 字段口径与 lease_contract 表及 HTTP 接口保持一致:
//   - 金额(monthly_rent/deposit)用 string 承载 decimal ——
//     protobuf 没有 decimal 类型, 用 double 会重现"金额精度丢失"这个已在项目内被禁止的问题;
//   - 面积(area_sqm)沿用 HTTP 契约的 double(它本就不是金额字段);
//   - 日期用 yyyy-MM-dd 字符串, 避免各语言时区解释不一致。
type Contract struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContractNo      string                 `protobuf:"bytes,2,opt,name=contract_no,json=contractNo,proto3" json:"contract_no,omitempty"`
	TenantId        int64                  `protobuf:"varint,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantName      string                 `protobuf:"bytes,4,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	ZoneCode        string                 `protobuf:"bytes,5,opt,name=zone_code,json=zoneCode,proto3" json:"zone_code,omitempty"`
	AreaSqm         float64                `protobuf:"fixed64,6,opt,name=area_sqm,json=areaSqm,proto3" json:"area_sqm,omitempty"`
	MonthlyRent     string                 `protobuf:"bytes,7,opt,name=monthly_rent,json=monthlyRent,proto3" json:"monthly_rent,omitempty"`                 // decimal 字符串
	Deposit         string                 `protobuf:"bytes,8,opt,name=deposit,proto3" json:"deposit,omitempty"`                                            // decimal 字符串
	StartDate       string                 `protobuf:"bytes,9,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                       // yyyy-MM-dd
	EndDate         string                 `protobuf:"bytes,10,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                            // yyyy-MM-dd
	Status          int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                            // 1待生效 2生效中 3已到期 4已终止
	AutoRenew       bool                   `protobuf:"varint,12,opt,name=auto_renew,json=autoRenew,proto3" json:"auto_renew,omitempty"`                     // 是否约定自动续约
	RenewNoticeDays int64                  `protobuf:"varint,13,opt,name=renew_notice_days,json=renewNoticeDays,proto3" json:"renew_notice_days,omitempty"` // 到期前多少天进入续签提醒窗口
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_leasing_leasing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_leasing_leasing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_leasing_leasing_proto_rawDescGZIP(), []int{2}
}

func (x *Contract) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contract) GetContractNo() string {
	if x != nil {
		return x.ContractNo
	}
	return ""
}

func (x *Contract) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Contract) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *Contract) GetZoneCode() string {
	if x != nil {
		return x.ZoneCode
	}
	return ""
}

func (x *Contract) GetAreaSqm() float64 {
	if x != nil {
		return x.AreaSqm
	}
	return 0
}

func (x *Contract) GetMonthlyRent() string {
	if x != nil {
		return x.MonthlyRent
	}
	return ""
}

func (x *Contract) GetDeposit() string {
	if x != nil {
		return x.Deposit
	}
	return ""
}

func (x *Contract) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Contract) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Contract) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Contract) GetAutoRenew() bool {
	if x != nil {
		return x.AutoRenew
	}
	return false
}

func (x *Contract) GetRenewNoticeDays() int64 {
	if x != nil {
		return x.RenewNoticeDays
	}
	return 0
}

// GetOccupancyReq 入驻率查询请求
type GetOccupancyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // 园区ID; 0 表示不过滤
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOccupancyReq) Reset() {
	*x = GetOccupancyReq{}
	mi := &file_leasing_leasing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOccupancyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOccupancyReq) ProtoMessage() {}

func (x *GetOccupancyReq) ProtoReflect() protoreflect.Message {
	mi := &file_leasing_leasing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOccupancyReq.ProtoReflect.Descriptor instead.
func (*GetOccupancyReq) Descriptor() ([]byte, []int) {
	return file_leasing_leasing_proto_rawDescGZIP(), []int{3}
}

func (x *GetOccupancyReq) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type GetOccupancyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalAreaSqm  float64                `protobuf:"fixed64,1,opt,name=total_area_sqm,json=totalAreaSqm,proto3" json:"total_area_sqm,omitempty"`    // 可租总面积(平方米)
	LeasedAreaSqm float64                `protobuf:"fixed64,2,opt,name=leased_area_sqm,json=leasedAreaSqm,proto3" json:"leased_area_sqm,omitempty"` // 已租面积(仅统计「生效中」合同)
	OccupancyRate float64                `protobuf:"fixed64,3,opt,name=occupancy_rate,json=occupancyRate,proto3" json:"occupancy_rate,omitempty"`   // 入驻率, 取值 0~1; 可租总面积为 0 时为 0(不返回 NaN)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOccupancyResp) Reset() {
	*x = GetOccupancyResp{}
	mi := &file_leasing_leasing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOccupancyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOccupancyResp) ProtoMessage() {}

func (x *GetOccupancyResp) ProtoReflect() protoreflect.Message {
	mi := &file_leasing_leasing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOccupancyResp.ProtoReflect.Descriptor instead.
func (*GetOccupancyResp) Descriptor() ([]byte, []int) {
	return file_leasing_leasing_proto_rawDescGZIP(), []int{4}
}

func (x *GetOccupancyResp) GetTotalAreaSqm() float64 {
	if x != nil {
		return x.TotalAreaSqm
	}
	return 0
}

func (x *GetOccupancyResp) GetLeasedAreaSqm() float64 {
	if x != nil {
		return x.LeasedAreaSqm
	}
	return 0
}

func (x *GetOccupancyResp) GetOccupancyRate() float64 {
	if x != nil {
		return x.OccupancyRate
	}
	return 0
}

var File_leasing_leasing_proto protoreflect.FileDescriptor

const file_leasing_leasing_proto_rawDesc = "" +
	"\n" +
	"\x15leasing/leasing.proto\x12\x0fonepark.leasing\x1a\x13common/common.proto\"=\n" +
	"\x0eGetContractReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\"H\n" +
	"\x0fGetContractResp\x125\n" +
	"\bcontract\x18\x01 \x01(\v2\x19.onepark.leasing.ContractR\bcontract\"\x8b\x03\n" +
	"\bContract\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcontract_no\x18\x02 \x01(\tR\n" +
	"contractNo\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\x03R\btenantId\x12\x1f\n" +
	"\vtenant_name\x18\x04 \x01(\tR\n" +
	"tenantName\x12\x1b\n" +
	"\tzone_code\x18\x05 \x01(\tR\bzoneCode\x12\x19\n" +
	"\barea_sqm\x18\x06 \x01(\x01R\aareaSqm\x12!\n" +
	"\fmonthly_rent\x18\a \x01(\tR\vmonthlyRent\x12\x18\n" +
	"\adeposit\x18\b \x01(\tR\adeposit\x12\x1d\n" +
	"\n" +
	"start_date\x18\t \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\n" +
	" \x01(\tR\aendDate\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"auto_renew\x18\f \x01(\bR\tautoRenew\x12*\n" +
	"\x11renew_notice_days\x18\r \x01(\x03R\x0frenewNoticeDays\".\n" +
	"\x0fGetOccupancyReq\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\x03R\btenantId\"\x87\x01\n" +
	"\x10GetOccupancyResp\x12$\n" +
	"\x0etotal_area_sqm\x18\x01 \x01(\x01R\ftotalAreaSqm\x12&\n" +
	"\x0fleased_area_sqm\x18\x02 \x01(\x01R\rleasedAreaSqm\x12%\n" +
	"\x0eoccupancy_rate\x18\x03 \x01(\x01R\roccupancyRate2\xed\x01\n" +
	"\x0eLeasingService\x124\n" +
	"\x04Ping\x12\x15.onepark.common.Empty\x1a\x15.onepark.common.Empty\x12P\n" +
	"\vGetContract\x12\x1f.onepark.leasing.GetContractReq\x1a .onepark.leasing.GetContractResp\x12S\n" +
	"\fGetOccupancy\x12 .onepark.leasing.GetOccupancyReq\x1a!.onepark.leasing.GetOccupancyRespB!Z\x1fonepark/proto/leasing;leasingpbb\x06proto3"

var (
	file_leasing_leasing_proto_rawDescOnce sync.Once
	file_leasing_leasing_proto_rawDescData []byte
)

func file_leasing_leasing_proto_rawDescGZIP() []byte {
	file_leasing_leasing_proto_rawDescOnce.Do(func() {
		file_leasing_leasing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_leasing_leasing_proto_rawDesc), len(file_leasing_leasing_proto_rawDesc)))
	})
	return file_leasing_leasing_proto_rawDescData
}

var file_leasing_leasing_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_leasing_leasing_proto_goTypes = []any{
	(*GetContractReq)(nil),   // 0: onepark.leasing.GetContractReq
	(*GetContractResp)(nil),  // 1: onepark.leasing.GetContractResp
	(*Contract)(nil),         // 2: onepark.leasing.Contract
	(*GetOccupancyReq)(nil),  // 3: onepark.leasing.GetOccupancyReq
	(*GetOccupancyResp)(nil), // 4: onepark.leasing.GetOccupancyResp
	(*common.Empty)(nil),     // 5: onepark.common.Empty
}
var file_leasing_leasing_proto_depIdxs = []int32{
	2, // 0: onepark.leasing.GetContractResp.contract:type_name -> onepark.leasing.Contract
	5, // 1: onepark.leasing.LeasingService.Ping:input_type -> onepark.common.Empty
	0, // 2: onepark.leasing.LeasingService.GetContract:input_type -> onepark.leasing.GetContractReq
	3, // 3: onepark.leasing.LeasingService.GetOccupancy:input_type -> onepark.leasing.GetOccupancyReq
	5, // 4: onepark.leasing.LeasingService.Ping:output_type -> onepark.common.Empty
	1, // 5: onepark.leasing.LeasingService.GetContract:output_type -> onepark.leasing.GetContractResp
	4, // 6: onepark.leasing.LeasingService.GetOccupancy:output_type -> onepark.leasing.GetOccupancyResp
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_leasing_leasing_proto_init() }
func file_leasing_leasing_proto_init() {
	if File_leasing_leasing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_leasing_leasing_proto_rawDesc), len(file_leasing_leasing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_leasing_leasing_proto_goTypes,
		DependencyIndexes: file_leasing_leasing_proto_depIdxs,
		MessageInfos:      file_leasing_leasing_proto_msgTypes,
	}.Build()
	File_leasing_leasing_proto = out.File
	file_leasing_leasing_proto_goTypes = nil
	file_leasing_leasing_proto_depIdxs = nil
}
