// Code generated by goctl. DO NOT EDIT.
// Source: shadow.proto
// 注意: GetShadow/UpdateDesired/UpdateReported/EnsureShadow 四个方法为 proto 扩展后手动补充,
// 后续重新生成骨架时需确认方法未被覆盖.

package server

import (
	"context"

	"onepark/app/shadow-service/internal/logic"
	"onepark/app/shadow-service/internal/svc"
	"onepark/proto/shadow"
)

type ShadowServer struct {
	svcCtx *svc.ServiceContext
	shadow.UnimplementedShadowServer
}

func NewShadowServer(svcCtx *svc.ServiceContext) *ShadowServer {
	return &ShadowServer{
		svcCtx: svcCtx,
	}
}

func (s *ShadowServer) Ping(ctx context.Context, in *shadow.Request) (*shadow.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *ShadowServer) GetShadow(ctx context.Context, in *shadow.GetShadowReq) (*shadow.GetShadowResp, error) {
	l := logic.NewGetShadowLogic(ctx, s.svcCtx)
	return l.GetShadow(in)
}

func (s *ShadowServer) UpdateDesired(ctx context.Context, in *shadow.UpdateDesiredReq) (*shadow.UpdateShadowResp, error) {
	l := logic.NewUpdateDesiredLogic(ctx, s.svcCtx)
	return l.UpdateDesired(in)
}

func (s *ShadowServer) UpdateReported(ctx context.Context, in *shadow.UpdateReportedReq) (*shadow.UpdateShadowResp, error) {
	l := logic.NewUpdateReportedLogic(ctx, s.svcCtx)
	return l.UpdateReported(in)
}

func (s *ShadowServer) EnsureShadow(ctx context.Context, in *shadow.EnsureShadowReq) (*shadow.EnsureShadowResp, error) {
	l := logic.NewEnsureShadowLogic(ctx, s.svcCtx)
	return l.EnsureShadow(in)
}
