// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/video-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/video/camera",
				Handler: AddCameraHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/video/cameras",
				Handler: ListCamerasHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/video/stream/:id",
				Handler: GetStreamHandler(serverCtx),
			},
		},
	)
}
