// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/video-service/internal/svc"
	"onepark/common/health"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/video/camera",
				Handler: AddCameraHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/video/cameras",
				Handler: ListCamerasHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/video/stream/:id",
				Handler: GetStreamHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/video/camera/:id",
				Handler: GetCameraHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/video/camera/:id",
				Handler: UpdateCameraHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/video/camera/:id",
				Handler: DeleteCameraHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/video/record-plan",
				Handler: CreateRecordPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/video/record-plans",
				Handler: ListRecordPlansHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/video/record-plan/:id",
				Handler: GetRecordPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/video/record-plan/:id",
				Handler: UpdateRecordPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/video/record-plan/:id",
				Handler: DeleteRecordPlanHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/video/playback",
				Handler: PlaybackHandler(serverCtx),
			},
			{Method: http.MethodGet, Path: "/health", Handler: health.Handler(serverCtx.DB, nil)},
		},
	)
}
