// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: access/access.proto

package accesspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "onepark/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AccessControlService_Ping_FullMethodName = "/onepark.access.AccessControlService/Ping"
)

// AccessControlServiceClient is the client API for AccessControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessControlServiceClient interface {
	// TODO: 业务接口由各服务负责人按 OpenViking 记忆中的接口清单补充
	Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
}

type accessControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessControlServiceClient(cc grpc.ClientConnInterface) AccessControlServiceClient {
	return &accessControlServiceClient{cc}
}

func (c *accessControlServiceClient) Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, AccessControlService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessControlServiceServer is the server API for AccessControlService service.
// All implementations must embed UnimplementedAccessControlServiceServer
// for forward compatibility
type AccessControlServiceServer interface {
	// TODO: 业务接口由各服务负责人按 OpenViking 记忆中的接口清单补充
	Ping(context.Context, *common.Empty) (*common.Empty, error)
	mustEmbedUnimplementedAccessControlServiceServer()
}

// UnimplementedAccessControlServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccessControlServiceServer struct {
}

func (UnimplementedAccessControlServiceServer) Ping(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAccessControlServiceServer) mustEmbedUnimplementedAccessControlServiceServer() {}

// UnsafeAccessControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessControlServiceServer will
// result in compilation errors.
type UnsafeAccessControlServiceServer interface {
	mustEmbedUnimplementedAccessControlServiceServer()
}

func RegisterAccessControlServiceServer(s grpc.ServiceRegistrar, srv AccessControlServiceServer) {
	s.RegisterService(&AccessControlService_ServiceDesc, srv)
}

func _AccessControlService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessControlServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessControlService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessControlServiceServer).Ping(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessControlService_ServiceDesc is the grpc.ServiceDesc for AccessControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepark.access.AccessControlService",
	HandlerType: (*AccessControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _AccessControlService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access/access.proto",
}
