// Code generated by goctl. DO NOT EDIT.
package types

type DispatchTask struct {
	Id         int64  `json:"id"`
	TenantId   int64  `json:"tenant_id"`
	Title      string `json:"title"`
	AssigneeId int64  `json:"assignee_id"`
	Priority   int32  `json:"priority"`
	Status     int32  `json:"status"`
	CreatedAt  int64  `json:"created_at"`
}

type ListDispatchReq struct {
	TenantId int64 `form:"tenant_id,optional"`
	Status   int32 `form:"status,optional"`
}

type ListDispatchResp struct {
	Total int64           `json:"total"`
	List  []*DispatchTask `json:"list"`
}
