// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type DispatchTask struct {
	Id           int64  `json:"id"`
	TaskNo       string `json:"task_no"`
	Title        string `json:"title"`
	Source       int32  `json:"source"`    // 1 人工创建 2 告警自动创建
	AlarmId      string `json:"alarm_id"`  // 来源告警 ID(自动创建时非空)
	ZoneCode     string `json:"zone_code"` // 事发区域, 用于就近指派
	Priority     int32  `json:"priority"`  // 1 紧急 2 高 3 普通
	Status       int32  `json:"status"`    // 1 待指派 2 已指派 3 处理中 4 已完成 5 已关闭
	AssigneeId   int64  `json:"assignee_id"`
	AssigneeName string `json:"assignee_name"`
	Description  string `json:"description"`
	CreatedAt    int64  `json:"created_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type TaskAssignReq struct {
	Id         int64 `path:"id"`
	AssigneeId int64 `json:"assignee_id,default=0"` // 0 = 走自动指派(值班+技能+就近+负载)
}

type TaskAssignResp struct {
	Id           int64  `json:"id"`
	Status       int32  `json:"status"`
	AssigneeId   int64  `json:"assignee_id"`
	AssigneeName string `json:"assignee_name"`
}

type TaskCreateReq struct {
	Title       string `json:"title"`
	Source      int32  `json:"source,default=1"`
	ZoneCode    string `json:"zone_code"`
	Priority    int32  `json:"priority,default=3"`
	Description string `json:"description,optional"`
}

type TaskCreateResp struct {
	Id     int64  `json:"id"`
	TaskNo string `json:"task_no"`
	Status int32  `json:"status"`
}

type TaskDetailReq struct {
	Id int64 `path:"id"`
}

type TaskDetailResp struct {
	Task DispatchTask `json:"task"`
}

type TaskListReq struct {
	Status   int32 `form:"status,default=0"`   // 0 表示不限
	Priority int32 `form:"priority,default=0"` // 0 表示不限
	Page     int64 `form:"page,default=1"`
	PageSize int64 `form:"page_size,default=10"`
}

type TaskListResp struct {
	Total int64          `json:"total"`
	List  []DispatchTask `json:"list"`
}

type TaskStatusReq struct {
	Id     int64  `path:"id"`
	Action string `json:"action"`
	Remark string `json:"remark,optional"`
}

type TaskStatusResp struct {
	Id     int64 `json:"id"`
	Status int32 `json:"status"`
}
