// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/visitor-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/visitor/checkin",
				Handler: VisitorCheckinHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/visitor/checkout",
				Handler: VisitorCheckoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/visitor/invite",
				Handler: VisitorInviteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/visitors",
				Handler: ListVisitorsHandler(serverCtx),
			},
		},
	)
}
