// Code generated by goctl. DO NOT EDIT.
//
// 本文件声明 visitor-service 的全部 HTTP 路由并注册到 go-zero rest.Server.
// 注意: 这里的 Path 是"服务内网直连路径"; 对外统一经根目录 gateway(8080) 以 /api/visitor 前缀转发.
package handler

import (
	"net/http"

	"onepark/app/visitor-service/internal/svc"
	"onepark/common/health"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 把本服务的 HTTP 路由挂载到 go-zero HTTP 服务器.
// 入参 server: go-zero 服务器实例; serverCtx: 全局依赖(DB/Redis/M1 device gRPC 客户端等).
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 访客扫码签入(核销 + 调 M1 开门)
				Method:  http.MethodPost,
				Path:    "/api/visitor/checkin",
				Handler: VisitorCheckinHandler(serverCtx),
			},
			{
				// 访客签出
				Method:  http.MethodPost,
				Path:    "/api/visitor/checkout",
				Handler: VisitorCheckoutHandler(serverCtx),
			},
			{
				// 发起访客邀请(生成二维码)
				Method:  http.MethodPost,
				Path:    "/api/visitor/invite",
				Handler: VisitorInviteHandler(serverCtx),
			},
			{
				// 访客记录分页列表
				Method:  http.MethodGet,
				Path:    "/api/visitors",
				Handler: ListVisitorsHandler(serverCtx),
			},
			{
				// 访客详情+门禁进出轨迹(P2: 签入产生的门禁动作留痕与访客记录关联)
				Method:  http.MethodGet,
				Path:    "/api/visitor/:id",
				Handler: GetVisitorDetailHandler(serverCtx),
			},
		{Method: http.MethodGet, Path: "/health", Handler: health.Handler(serverCtx.DB, serverCtx.Redis)},
		},
	)
}
