// Code generated by goctl. DO NOT EDIT.
//
// 本文件为 visitor-service 的 HTTP 出入参类型定义(由 visitor.api 生成).
package types

// ListVisitorReq 访客记录分页查询请求.
type ListVisitorReq struct {
	Status   int8  `form:"status,optional"` // 状态筛选(可选): 1待使用 2已签入 3已签出 4已过期
	Page     int64 `form:"page"`            // 页码(从1开始)
	PageSize int64 `form:"page_size"`       // 每页大小
}

// VisitorCheckinReq 访客签入请求(多方式核验).
// VerifyChannel=1(默认) 用 QRCode; 其余方式(2手机号/3身份证/4人脸/5工牌) 用 Credential 传对应维度凭证值.
type VisitorCheckinReq struct {
	QRCode        string `json:"qr_code,optional"`        // 加密二维码内容(核验方式=1)
	VerifyChannel int8   `json:"verify_channel,optional"` // 核验方式 1二维码(默认) 2手机号 3身份证 4人脸 5工牌
	Credential    string `json:"credential,optional"`     // 非二维码方式的凭证值(手机号/身份证/人脸令牌/工牌号)
}

// VisitorCheckinResp 签入响应.
type VisitorCheckinResp struct {
	Id        int64  `json:"id"`                 // 访客记录ID
	Status    int8   `json:"status"`             // 1待使用 2已签入 3已签出 4已过期
	CheckinAt int64  `json:"checkin_at"`         // 签入时间(秒级时间戳)
	DeviceID  string `json:"device_id,optional"` // 开门设备ID(M1 开门成功回填)
	OpenMsg   string `json:"open_msg,optional"`  // 开门结果提示(M1 降级时提示"请联系前台人工开门", 不阻断签入)
}

// VisitorCheckoutReq 访客签出请求(按Id或二维码, 二选一).
type VisitorCheckoutReq struct {
	Id     int64  `json:"id,optional"`      // 访客记录ID
	QRCode string `json:"qr_code,optional"` // 加密二维码内容
}

// VisitorCheckoutResp 签出响应.
type VisitorCheckoutResp struct {
	Id         int64 `json:"id"`          // 访客记录ID
	Status     int8  `json:"status"`      // 签出后状态(3已签出)
	CheckoutAt int64 `json:"checkout_at"` // 签出时间(秒级时间戳)
}

// VisitorInviteReq 发起访客邀请请求.
type VisitorInviteReq struct {
	VisitorName   string `json:"visitor_name"`            // 访客姓名
	VisitorPhone  string `json:"visitor_phone"`           // 访客手机号
	VisitTime     int64  `json:"visit_time"`              // 预期到访时间(秒级时间戳)
	ExpireTime    int64  `json:"expire_time"`             // 二维码过期时间(秒级时间戳)
	Reason        string `json:"reason,optional"`         // 来访原因
	IdNo          string `json:"id_no,optional"`          // 身份证号(核验方式=3, 加密存储)
	FaceToken     string `json:"face_token,optional"`     // 人脸特征令牌(核验方式=4)
	BadgeNo       string `json:"badge_no,optional"`       // 工牌号(核验方式=5)
	VerifyChannel int8   `json:"verify_channel,optional"` // 核验方式 1二维码(默认) 2手机号 3身份证 4人脸 5工牌
}

// VisitorInviteResp 邀请响应(返回加密二维码内容 + go-qrcode 渲染的二维码图片).
type VisitorInviteResp struct {
	Id       int64  `json:"id"`                // 访客记录ID
	QRCode   string `json:"qr_code"`           // 加密二维码内容(含签名+有效期)
	QrImage  string `json:"qr_image,optional"` // 二维码图片(base64 PNG, go-qrcode 渲染; 渲染失败为空)
	ExpireAt int64  `json:"expire_at"`         // 过期时间(秒级时间戳)
}

// VisitorItem 访客列表项.
type VisitorItem struct {
	Id           int64  `json:"id"`                   // 访客记录ID
	VisitorName  string `json:"visitor_name"`         // 访客姓名
	VisitorPhone string `json:"visitor_phone"`        // 访客手机号
	Status       int8   `json:"status"`               // 状态: 1待使用 2已签入 3已签出 4已过期
	VisitTime    int64  `json:"visit_time"`           // 预期到访时间(秒级时间戳)
	CheckinAt    int64  `json:"checkin_at,optional"`  // 签入时间(秒级时间戳)
	CheckoutAt   int64  `json:"checkout_at,optional"` // 签出时间(秒级时间戳)
	DeviceID     string `json:"device_id,optional"`   // 开门设备ID
}

// VisitorListResp 访客分页响应.
type VisitorListResp struct {
	Total int64         `json:"total"` // 总数
	List  []VisitorItem `json:"list"`  // 当前页数据
}

// VisitorIdReq 访客详情路径参数.
type VisitorIdReq struct {
	Id int64 `path:"id"` // 访客记录ID
}

// VisitorTrackItem 访客进出轨迹项(门禁动作留痕, 来源于 visitor_record 的动作字段).
type VisitorTrackItem struct {
	Action   string `json:"action"`             // invite(邀请生成码)/checkin_open_door(签入+门禁开门)/checkout(签出)/expired(过期失效)
	Time     int64  `json:"time"`               // 动作时间(秒级时间戳)
	DeviceId string `json:"device_id,optional"` // 开门设备ID(仅签入且 M1 开门成功时有值)
	Remark   string `json:"remark,optional"`    // 动作说明
}

// VisitorDetailResp 访客详情响应(含门禁进出轨迹, 供详情页展示与轨迹追溯).
type VisitorDetailResp struct {
	Id           int64              `json:"id"`                 // 访客记录ID
	InviterId    int64              `json:"inviter_id"`         // 邀请人ID
	VisitorName  string             `json:"visitor_name"`       // 访客姓名
	VisitorPhone string             `json:"visitor_phone"`      // 访客手机号
	Status       int8               `json:"status"`             // 1待使用 2已签入 3已签出 4已过期
	VisitTime    int64              `json:"visit_time"`         // 预期到访时间(秒级, 0未设置)
	ExpireTime   int64              `json:"expire_time"`        // 二维码过期时间(秒级, 0未设置)
	CheckinAt    int64              `json:"checkin_at"`         // 签入时间(秒级, 0未签入)
	CheckoutAt   int64              `json:"checkout_at"`        // 签出时间(秒级, 0未签出)
	DeviceId     string             `json:"device_id,optional"` // 签入开门设备ID
	Track        []VisitorTrackItem `json:"track"`              // 进出轨迹(按时间正序)
}

// AddVisitorBlocklistReq 访客黑名单新增/更新请求(P2).
// 手机号与身份证至少提供一个作为拉黑维度; 同租户下已生效同维度自动刷新而非重复插入.
type AddVisitorBlocklistReq struct {
	VisitorName   string `json:"visitor_name,optional"`   // 访客姓名
	Phone         string `json:"phone,optional"`          // 手机号(拉黑维度之一)
	IdNo          string `json:"id_no,optional"`          // 身份证号(拉黑维度之一, 加密存储)
	Reason        string `json:"reason,optional"`         // 拉黑原因
	EffectiveFrom int64  `json:"effective_from,optional"` // 生效起(秒级时间戳, 0=立即)
	EffectiveTo   int64  `json:"effective_to,optional"`   // 生效止(秒级时间戳, 0=永久)
}

// AddVisitorBlocklistResp 访客黑名单新增/更新响应
type AddVisitorBlocklistResp struct {
	Id int64 `json:"id"` // 黑名单记录ID
}

// UnblockVisitorBlocklistReq 访客黑名单解除请求(路径 id)
type UnblockVisitorBlocklistReq struct {
	Id int64 `path:"id"` // 黑名单记录ID
}

// UnblockVisitorBlocklistResp 访客黑名单解除响应
type UnblockVisitorBlocklistResp struct {
	Id     int64 `json:"id"`     // 黑名单记录ID
	Status int8  `json:"status"` // 解除后状态(2)
}
