// Code generated by goctl. DO NOT EDIT.
//
// 本文件为 visitor-service 的 HTTP 出入参类型定义(由 visitor.api 生成).
package types

// ListVisitorReq 访客记录分页查询请求.
type ListVisitorReq struct {
	Status   int8  `form:"status,optional"` // 状态筛选(可选): 1待使用 2已签入 3已签出 4已过期
	Page     int64 `form:"page"`            // 页码(从1开始)
	PageSize int64 `form:"page_size"`       // 每页大小
}

// VisitorCheckinReq 访客扫码签入请求.
type VisitorCheckinReq struct {
	QRCode string `json:"qr_code"` // 加密二维码内容(含签名+有效期)
}

// VisitorCheckinResp 签入响应.
type VisitorCheckinResp struct {
	Id        int64  `json:"id"`                 // 访客记录ID
	Status    int8   `json:"status"`             // 1待使用 2已签入 3已签出 4已过期
	CheckinAt int64  `json:"checkin_at"`         // 签入时间(秒级时间戳)
	DeviceID  string `json:"device_id,optional"` // 开门设备ID(M1 开门成功回填)
}

// VisitorCheckoutReq 访客签出请求(按Id或二维码, 二选一).
type VisitorCheckoutReq struct {
	Id     int64  `json:"id,optional"`      // 访客记录ID
	QRCode string `json:"qr_code,optional"` // 加密二维码内容
}

// VisitorCheckoutResp 签出响应.
type VisitorCheckoutResp struct {
	Id         int64 `json:"id"`          // 访客记录ID
	Status     int8  `json:"status"`      // 签出后状态(3已签出)
	CheckoutAt int64 `json:"checkout_at"` // 签出时间(秒级时间戳)
}

// VisitorInviteReq 发起访客邀请请求.
type VisitorInviteReq struct {
	VisitorName  string `json:"visitor_name"`    // 访客姓名
	VisitorPhone string `json:"visitor_phone"`   // 访客手机号
	VisitTime    int64  `json:"visit_time"`      // 预期到访时间(秒级时间戳)
	ExpireTime   int64  `json:"expire_time"`     // 二维码过期时间(秒级时间戳)
	Reason       string `json:"reason,optional"` // 来访原因
}

// VisitorInviteResp 邀请响应(返回加密二维码内容).
type VisitorInviteResp struct {
	Id       int64  `json:"id"`        // 访客记录ID
	QRCode   string `json:"qr_code"`   // 加密二维码内容(含签名+有效期)
	ExpireAt int64  `json:"expire_at"` // 过期时间(秒级时间戳)
}

// VisitorItem 访客列表项.
type VisitorItem struct {
	Id           int64  `json:"id"`                   // 访客记录ID
	VisitorName  string `json:"visitor_name"`         // 访客姓名
	VisitorPhone string `json:"visitor_phone"`        // 访客手机号
	Status       int8   `json:"status"`               // 状态: 1待使用 2已签入 3已签出 4已过期
	VisitTime    int64  `json:"visit_time"`           // 预期到访时间(秒级时间戳)
	CheckinAt    int64  `json:"checkin_at,optional"`  // 签入时间(秒级时间戳)
	CheckoutAt   int64  `json:"checkout_at,optional"` // 签出时间(秒级时间戳)
	DeviceID     string `json:"device_id,optional"`   // 开门设备ID
}

// VisitorListResp 访客分页响应.
type VisitorListResp struct {
	Total int64         `json:"total"` // 总数
	List  []VisitorItem `json:"list"`  // 当前页数据
}
