// Code generated by goctl. DO NOT EDIT.
package types

type ListVisitorReq struct {
	Status   int8  `form:"status,optional"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type VisitorCheckinReq struct {
	QRCode string `json:"qr_code"`
}

type VisitorCheckinResp struct {
	Id        int64 `json:"id"`
	Status    int8  `json:"status"`     // 1待使用 2已签入 3已签出 4已过期
	CheckinAt int64 `json:"checkin_at"` // 签入时间(秒级时间戳)
}

type VisitorCheckoutReq struct {
	Id     int64  `json:"id,optional"`
	QRCode string `json:"qr_code,optional"`
}

type VisitorCheckoutResp struct {
	Id         int64 `json:"id"`
	Status     int8  `json:"status"`
	CheckoutAt int64 `json:"checkout_at"` // 签出时间(秒级时间戳)
}

type VisitorInviteReq struct {
	VisitorName  string `json:"visitor_name"`    // 访客姓名
	VisitorPhone string `json:"visitor_phone"`   // 访客手机号
	VisitTime    int64  `json:"visit_time"`      // 预期到访时间(秒级时间戳)
	ExpireTime   int64  `json:"expire_time"`     // 二维码过期时间(秒级时间戳)
	Reason       string `json:"reason,optional"` // 来访原因
}

type VisitorInviteResp struct {
	Id       int64  `json:"id"`
	QRCode   string `json:"qr_code"`   // 加密二维码内容(含签名+有效期)
	ExpireAt int64  `json:"expire_at"` // 过期时间(秒级时间戳)
}

type VisitorItem struct {
	Id           int64  `json:"id"`
	VisitorName  string `json:"visitor_name"`
	VisitorPhone string `json:"visitor_phone"`
	Status       int8   `json:"status"`
	VisitTime    int64  `json:"visit_time"`
	CheckinAt    int64  `json:"checkin_at,optional"`
	CheckoutAt   int64  `json:"checkout_at,optional"`
}

type VisitorListResp struct {
	Total int64         `json:"total"`
	List  []VisitorItem `json:"list"`
}
