// Code generated by goctl. DO NOT EDIT.
//
// 本文件为 notice-service 的 HTTP 出入参类型定义(由 notice.api 生成).
package types

// CreateNoticeReq 发布公告请求.
type CreateNoticeReq struct {
	Title     string `json:"title"`               // 标题
	Content   string `json:"content"`             // 正文
	Type      int8   `json:"type"`                // 1通知 2公告 3活动 4停水 5停电
	Top       bool   `json:"top,optional"`        // 是否置顶
	PublishAt int64  `json:"publish_at,optional"` // 定时发布(秒级时间戳), 0=立即发布
}

// ListNoticeReq 公告分页查询请求.
type ListNoticeReq struct {
	Type     int8  `form:"type,optional"`   // 类型筛选(可选)
	Status   int8  `form:"status,optional"` // 状态筛选(可选): 1草稿 2已发布 3已撤回
	Page     int64 `form:"page"`            // 页码(从1开始)
	PageSize int64 `form:"page_size"`       // 每页大小
}

// NoticeItem 公告列表项.
type NoticeItem struct {
	Id        int64  `json:"id"`                  // 公告ID
	Title     string `json:"title"`               // 标题
	Type      int8   `json:"type"`                // 1通知 2公告 3活动 4停水 5停电
	Status    int8   `json:"status"`              // 1草稿 2已发布 3已撤回
	Top       bool   `json:"top"`                 // 是否置顶
	PublishAt int64  `json:"publish_at,optional"` // 发布时间(秒级时间戳)
	CreatedAt int64  `json:"created_at"`          // 创建时间(秒级时间戳)
}

// NoticeListResp 公告分页响应.
type NoticeListResp struct {
	Total int64        `json:"total"` // 总数
	List  []NoticeItem `json:"list"`  // 当前页数据
}

// NoticeResp 发布公告响应.
type NoticeResp struct {
	Id        int64  `json:"id"`                  // 公告ID
	Title     string `json:"title"`               // 标题
	Type      int8   `json:"type"`                // 1通知 2公告 3活动 4停水 5停电
	Status    int8   `json:"status"`              // 1草稿 2已发布 3已撤回
	Top       bool   `json:"top"`                 // 是否置顶
	PublishAt int64  `json:"publish_at,optional"` // 发布时间(秒级时间戳)
}
