// Code generated by goctl. DO NOT EDIT.
package types

type CreateNoticeReq struct {
	Title     string `json:"title"`
	Content   string `json:"content"`
	Type      int8   `json:"type"`                // 1通知 2公告 3活动 4停水 5停电
	Top       bool   `json:"top,optional"`        // 是否置顶
	PublishAt int64  `json:"publish_at,optional"` // 定时发布(秒级时间戳), 0=立即发布
}

type ListNoticeReq struct {
	Type     int8  `form:"type,optional"`
	Status   int8  `form:"status,optional"`
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

type NoticeItem struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Type      int8   `json:"type"`
	Status    int8   `json:"status"`
	Top       bool   `json:"top"`
	PublishAt int64  `json:"publish_at,optional"`
	CreatedAt int64  `json:"created_at"`
}

type NoticeListResp struct {
	Total int64        `json:"total"`
	List  []NoticeItem `json:"list"`
}

type NoticeResp struct {
	Id        int64  `json:"id"`
	Title     string `json:"title"`
	Type      int8   `json:"type"`
	Status    int8   `json:"status"` // 1草稿 2已发布 3已撤回
	Top       bool   `json:"top"`
	PublishAt int64  `json:"publish_at,optional"`
}
