// Code generated by goctl. DO NOT EDIT.
package types

type LeaseContract struct {
	Id         int64  `json:"id"`
	TenantId   int64  `json:"tenant_id"`
	ContractNo string `json:"contract_no"`
	Title      string `json:"title"`
	Lessor     string `json:"lessor"`
	Lessee     string `json:"lessee"`
	Area       int64  `json:"area"`
	StartDate  string `json:"start_date"`
	EndDate    string `json:"end_date"`
	Rent       int64  `json:"rent"`
	Status     int32  `json:"status"`
}

type ListLeaseReq struct {
	TenantId int64 `form:"tenant_id,optional"`
	Page     int64 `form:"page,optional"`
	PageSize int64 `form:"page_size,optional"`
}

type ListLeaseResp struct {
	Total int64            `json:"total"`
	List  []*LeaseContract `json:"list"`
}
