// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/device-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/device/:id",
				Handler: DeviceDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/device/:id",
				Handler: DeviceDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/device/:id/command",
				Handler: DeviceCommandHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/device/register",
				Handler: DeviceRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/devices",
				Handler: DeviceListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/product",
				Handler: ProductCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/product/:key",
				Handler: ProductDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/product/:key",
				Handler: ProductUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/products",
				Handler: ProductListHandler(serverCtx),
			},
		},
	)
}
