// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/energy-agent-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/agent/inspect",
				Handler: InspectHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/agent/suggestion/approve",
				Handler: ApproveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/agent/suggestions",
				Handler: SuggestionListHandler(serverCtx),
			},
		},
	)
}
