// Code generated by goctl. DO NOT EDIT.
package types

type ApproveRequest struct {
	Id       int64  `json:"id"`
	Approved bool   `json:"approved"`         // true通过 false驳回
	Reviewer string `json:"reviewer"`         // 审批人
	Comment  string `json:"comment,optional"` // 审批意见
}

type ApproveResponse struct {
	Id          int64  `json:"id"`
	Status      int64  `json:"status"`      // 2已通过 3已驳回
	WorkorderNo string `json:"workorderNo"` // 已转出的工单号, 未转为空串
}

type EvidenceItem struct {
	Key   string  `json:"key"`   // 如 baseline / actual / deviation / topDevice
	Label string  `json:"label"` // 中文名, 直接展示
	Value float64 `json:"value"`
	Unit  string  `json:"unit"` // 度 / 百分比
}

type InspectRequest struct {
	ZoneId     string `json:"zoneId,optional"`     // 只查某个区域, 不传表示全园区
	StatDate   string `json:"statDate,optional"`   // 统计哪天, 如 2026-09-16, 不传默认昨天
	DisableLLM bool   `json:"disableLLM,optional"` // 传 true 表示本次不调大模型, 用来对比"有无大模型"的效果差异
}

type InspectResponse struct {
	RunNo       string           `json:"runNo"` // 本次运行编号, 可据此查轨迹
	StatDate    string           `json:"statDate"`
	ZoneCount   int64            `json:"zoneCount"`  // 扫了几个区域
	FindCount   int64            `json:"findCount"`  // 发现几条异常
	LLMEnabled  bool             `json:"llmEnabled"` // 有没有调大模型
	LLMModel    string           `json:"llmModel"`
	CostMs      int64            `json:"costMs"`
	Suggestions []SuggestionItem `json:"suggestions"`
}

type SuggestionItem struct {
	Id         int64   `json:"id"`
	ZoneId     string  `json:"zoneId"`
	DeviceId   string  `json:"deviceId"` // 全区域类建议为空
	Category   string  `json:"category"` // night_idle / device_spike / zone_surge / meter_backward / data_missing
	Severity   int64   `json:"severity"` // 3高 2中 1低
	Title      string  `json:"title"`
	Reason     string  `json:"reason"`     // 判断依据(大模型润色后的人话)
	Confidence float64 `json:"confidence"` // 0到1
	Action     string  `json:"action"`     // 建议动作
	Status     int64   `json:"status"`     // 1待审批 2已通过 3已驳回 4已转工单
}

type SuggestionListRequest struct {
	ZoneId   string `form:"zoneId,optional"`
	Category string `form:"category,optional"` // 按异常类型筛选
	Status   string `form:"status,optional"`   // 1待审批 2已通过 3已驳回 4已转工单
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"pageSize,optional"`
}

type SuggestionListResponse struct {
	Total    int64            `json:"total"`
	Page     int64            `json:"page"`
	PageSize int64            `json:"pageSize"`
	List     []SuggestionItem `json:"list"`
}
