// Code generated by goctl. DO NOT EDIT.
//
// 本文件为 workorder-service 的 HTTP 出入参类型定义(由 workorder.api 生成).
// 约定: 入参字段带 path/form/json 标签; 出参字段带 json 标签. 结尾 optional 表示可选.
package types

// AssignWorkOrderReq 派单请求.
type AssignWorkOrderReq struct {
	Id           int64 `path:"id"`                     // 工单ID(路径参数)
	AssigneeID   int64 `json:"assignee_id"`            // 处理人ID
	DepartmentID int64 `json:"department_id,optional"` // 处理部门ID(可选)
}

// CreateWorkOrderReq 创建工单请求.
type CreateWorkOrderReq struct {
	Type        int8   `json:"type"`        // 工单类型: 1报修 2投诉 3巡检 4保洁 5装修 6搬运 7其他
	Title       string `json:"title"`       // 标题
	Description string `json:"description"` // 详细描述
	Priority    int8   `json:"priority"`    // 优先级: 1紧急 2普通 3低
	Location    string `json:"location"`    // 位置/楼栋房号
}

// IdReq 通用路径参数请求(仅含主键 id).
type IdReq struct {
	Id int64 `path:"id"` // 主键ID(路径参数)
}

// ListWorkOrderReq 工单列表查询请求.
// 注意: Status 使用指针类型(*int8), 以 nil 区分"未传状态筛选"与"筛选待派单(status=0)".
// 原 int8 零值 0 与合法态"待派单"冲突, 导致无法按待派单精确筛选(审查问题2).
type ListWorkOrderReq struct {
	Status     *int8 `form:"status,optional"`      // 状态筛选(可选, nil 表示不限; 0=待派单)
	Type       int8  `form:"type,optional"`        // 类型筛选(可选)
	AssigneeID int64 `form:"assignee_id,optional"` // 处理人筛选(可选)
	Page       int64 `form:"page"`                 // 页码(从1开始)
	PageSize   int64 `form:"page_size"`            // 每页大小
}

// UpdateWorkOrderStatusReq 工单状态流转请求.
type UpdateWorkOrderStatusReq struct {
	Id     int64  `path:"id"`              // 工单ID(路径参数)
	Action string `json:"action"`          // 动作: submit(处理中→待验收) approve(待验收→已完成) reject(待验收→处理中) close(任意活跃态→已关闭)
	Remark string `json:"remark,optional"` // 流转备注(验收意见/驳回原因等)
}

// WorkOrderDetailResp 工单详情响应.
type WorkOrderDetailResp struct {
	Id           int64  `json:"id"`                   // 工单ID
	TenantID     int64  `json:"tenant_id"`            // 园区ID(RBAC 隔离)
	OrderNo      string `json:"order_no"`             // 工单号 WO-YYYYMMDD-XXXX
	Type         int8   `json:"type"`                 // 工单类型
	Title        string `json:"title"`                // 标题
	Description  string `json:"description"`          // 详细描述
	ReporterID   int64  `json:"reporter_id"`          // 报修/发起人
	AssigneeID   int64  `json:"assignee_id"`          // 处理人
	DepartmentID int64  `json:"department_id"`        // 处理部门
	Status       int8   `json:"status"`               // 0待派单 1处理中 2待验收 3已完成 4已关闭
	Priority     int8   `json:"priority"`             // 1紧急 2普通 3低
	Location     string `json:"location"`             // 位置/楼栋房号
	Attachments  string `json:"attachments"`          // MinIO 对象Key列表(JSON)
	Version      int64  `json:"version"`              // 乐观锁版本
	CreatedAt    int64  `json:"created_at"`           // 创建时间(秒级时间戳)
	UpdatedAt    int64  `json:"updated_at"`           // 更新时间(秒级时间戳)
	FinishedAt   int64  `json:"finished_at,optional"` // 完成/关闭时间(秒级时间戳)
}

// WorkOrderItem 工单列表项(列表页精简字段).
type WorkOrderItem struct {
	Id         int64  `json:"id"`          // 工单ID
	OrderNo    string `json:"order_no"`    // 工单号
	Type       int8   `json:"type"`        // 工单类型
	Title      string `json:"title"`       // 标题
	Status     int8   `json:"status"`      // 当前状态
	Priority   int8   `json:"priority"`    // 优先级
	AssigneeID int64  `json:"assignee_id"` // 处理人
	CreatedAt  int64  `json:"created_at"`  // 创建时间(秒级时间戳)
}

// WorkOrderListResp 工单分页列表响应.
type WorkOrderListResp struct {
	Total int64           `json:"total"` // 总数
	List  []WorkOrderItem `json:"list"`  // 当前页数据
}

// WorkOrderResp 工单简要响应(创建/派单/流转后返回).
type WorkOrderResp struct {
	Id      int64  `json:"id"`       // 主键ID
	OrderNo string `json:"order_no"` // 工单号
	Status  int8   `json:"status"`   // 当前状态
}

// WorkOrderStatisticsResp 工单统计看板响应(P2: 物业后台统计端点, 与 gRPC ListWorkOrders 聚合字段对齐).
type WorkOrderStatisticsResp struct {
	Total             int64   `json:"total"`               // 工单总数
	PendingCount      int64   `json:"pending_count"`       // 待处理(待派单+处理中)
	TodayCount        int64   `json:"today_count"`         // 今日新建
	CompletedToday    int64   `json:"completed_today"`     // 今日完成
	AvgProcessMinutes float64 `json:"avg_process_minutes"` // 平均处理时长(分钟)
	CompletionRate    float64 `json:"completion_rate"`     // 完成率(0~100)
}
