// Code generated by goctl. DO NOT EDIT.
package types

type AssignWorkOrderReq struct {
	Id           int64 `path:"id"`                     // 工单ID(路径参数)
	AssigneeID   int64 `json:"assignee_id"`            // 处理人ID
	DepartmentID int64 `json:"department_id,optional"` // 处理部门ID(可选)
}

type CreateWorkOrderReq struct {
	Type        int8   `json:"type"`        // 工单类型: 1报修 2投诉 3巡检 4保洁 5装修 6搬运 7其他
	Title       string `json:"title"`       // 标题
	Description string `json:"description"` // 详细描述
	Priority    int8   `json:"priority"`    // 优先级: 1紧急 2普通 3低
	Location    string `json:"location"`    // 位置/楼栋房号
}

type IdReq struct {
	Id int64 `path:"id"` // 主键ID(路径参数)
}

type ListWorkOrderReq struct {
	Status     int8  `form:"status,optional"`      // 状态筛选(可选)
	Type       int8  `form:"type,optional"`        // 类型筛选(可选)
	AssigneeID int64 `form:"assignee_id,optional"` // 处理人筛选(可选)
	Page       int64 `form:"page"`                 // 页码(从1开始)
	PageSize   int64 `form:"page_size"`            // 每页大小
}

type UpdateWorkOrderStatusReq struct {
	Id     int64  `path:"id"`              // 工单ID(路径参数)
	Action string `json:"action"`          // 动作: submit(处理中→待验收) approve(待验收→已完成) reject(待验收→处理中) close(任意活跃态→已关闭)
	Remark string `json:"remark,optional"` // 流转备注(验收意见/驳回原因等)
}

type WorkOrderDetailResp struct {
	Id           int64  `json:"id"`
	TenantID     int64  `json:"tenant_id"` // 园区ID(RBAC 隔离)
	OrderNo      string `json:"order_no"`
	Type         int8   `json:"type"`
	Title        string `json:"title"`
	Description  string `json:"description"`
	ReporterID   int64  `json:"reporter_id"`   // 报修/发起人
	AssigneeID   int64  `json:"assignee_id"`   // 处理人
	DepartmentID int64  `json:"department_id"` // 处理部门
	Status       int8   `json:"status"`
	Priority     int8   `json:"priority"`
	Location     string `json:"location"`
	Attachments  string `json:"attachments"`          // MinIO 对象Key列表(JSON)
	Version      int64  `json:"version"`              // 乐观锁版本
	CreatedAt    int64  `json:"created_at"`           // 创建时间(秒级时间戳)
	UpdatedAt    int64  `json:"updated_at"`           // 更新时间(秒级时间戳)
	FinishedAt   int64  `json:"finished_at,optional"` // 完成/关闭时间(秒级时间戳)
}

type WorkOrderItem struct {
	Id         int64  `json:"id"`
	OrderNo    string `json:"order_no"`
	Type       int8   `json:"type"`
	Title      string `json:"title"`
	Status     int8   `json:"status"`
	Priority   int8   `json:"priority"`
	AssigneeID int64  `json:"assignee_id"`
	CreatedAt  int64  `json:"created_at"` // 创建时间(秒级时间戳)
}

type WorkOrderListResp struct {
	Total int64           `json:"total"` // 总数
	List  []WorkOrderItem `json:"list"`  // 当前页数据
}

type WorkOrderResp struct {
	Id      int64  `json:"id"`       // 主键ID
	OrderNo string `json:"order_no"` // 工单号
	Status  int8   `json:"status"`   // 当前状态
}
