// Code generated by goctl. DO NOT EDIT.
//
// 本文件声明 parking-service 的全部 HTTP 路由并注册到 go-zero rest.Server.
// 注意: 这里的 Path 是"服务内网直连路径"; 对外统一经根目录 gateway(8080) 以 /api/parking 前缀转发.
package handler

import (
	"net/http"

	"onepark/app/parking-service/internal/svc"
	"onepark/common/health"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 把本服务的 HTTP 路由挂载到 go-zero HTTP 服务器.
// 入参 server: go-zero 服务器实例; serverCtx: 全局依赖(DB/Redis/Kafka 生产者).
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 在场车辆列表
				Method:  http.MethodGet,
				Path:    "/api/parking/active",
				Handler: ActiveParkingHandler(serverCtx),
			},
			{
				// 车辆入场
				Method:  http.MethodPost,
				Path:    "/api/parking/entry",
				Handler: ParkingEntryHandler(serverCtx),
			},
			{
				// 车辆离场(计费)
				Method:  http.MethodPost,
				Path:    "/api/parking/exit",
				Handler: ParkingExitHandler(serverCtx),
			},
			{
				// 停车记录分页列表
				Method:  http.MethodGet,
				Path:    "/api/parking/records",
				Handler: ListParkingHandler(serverCtx),
			},
			{
				// 创建月卡(P2)
				Method:  http.MethodPost,
				Path:    "/api/parking/monthly-card",
				Handler: CreateMonthlyCardHandler(serverCtx),
			},
			{
				// 月卡续费(P2)
				Method:  http.MethodPost,
				Path:    "/api/parking/monthly-card/renew",
				Handler: RenewMonthlyCardHandler(serverCtx),
			},
			{
				// 月卡停用(P2, 幂等)
				Method:  http.MethodPost,
				Path:    "/api/parking/monthly-card/disable",
				Handler: DisableMonthlyCardHandler(serverCtx),
			},
			{
				// 月卡		{
				// 月卡分页列表+到期提醒筛选(P2)
				Method:  http.MethodGet,
				Path:    "/api/parking/monthly-cards",
				Handler: ListMonthlyCardsHandler(serverCtx),
			},
			{
				// 停车计费规则查询(P2 计费规则配置接口): 返回当前生效规则, 无配置为 null
				Method:  http.MethodGet,
				Path:    "/api/parking/fee-rule",
				Handler: GetParkingFeeRuleHandler(serverCtx),
			},
			{
				// 停车计费规则保存(P2 计费规则配置接口): 新增一条生效规则
				Method:  http.MethodPost,
				Path:    "/api/parking/fee-rule",
				Handler: UpsertParkingFeeRuleHandler(serverCtx),
			},
			{Method: http.MethodGet, Path: "/health", Handler: health.Handler(serverCtx.DB, serverCtx.Redis)},
		},
	)
}
