// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/energy-analysis-service/internal/svc"
	"onepark/common/health"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/energy/daily",
				Handler: DailyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/energy/monthly",
				Handler: MonthlyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/energy/zone",
				Handler: ZoneHandler(serverCtx),
			},
		{Method: http.MethodGet, Path: "/health", Handler: health.Handler(nil, nil)},
		},
	)
}
