// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/dashboard-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/overview",
				Handler: OverviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/query",
				Handler: QueryHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/dashboard"),
	)
}
