// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	dashboard "onepark/app/dashboard-service/internal/handler/dashboard"
	"onepark/app/dashboard-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/home",
				Handler: dashboard.HomeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/overview",
				Handler: dashboard.OverviewHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/dashboard"),
	)
}
