// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/dashboard-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: DashboardHandler(serverCtx),
			},
		},
	)

	// 手写路由(联调 M4 接口54): 重新生成 routes.go 后需补回
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/dashboard/energy/card",
				Handler: EnergyCardHandler(serverCtx),
			},
		},
	)
}
