// Code generated by goctl. DO NOT EDIT.
package types

type DeviceCommandReq struct {
	DeviceID    string `path:"id"`
	CommandType string `json:"commandType"`
	Payload     string `json:"payload"`
	Mode        int8   `json:"mode,default=1"`
}

type DeviceCommandResp struct {
	RequestID string `json:"requestId"`
	Status    int8   `json:"status"`
}

type DeviceDeleteReq struct {
	DeviceID string `path:"id"`
}

type DeviceDetailReq struct {
	DeviceID string `path:"id"`
}

type DeviceDetailResp struct {
	DeviceID     string `json:"deviceId"`
	DeviceName   string `json:"deviceName"`
	ProductKey   string `json:"productKey"`
	ParkID       string `json:"parkId"`
	BuildingID   string `json:"buildingId"`
	Floor        string `json:"floor"`
	Location     string `json:"location"`
	Status       int8   `json:"status"`
	LastOnlineAt string `json:"lastOnlineAt,optional"`
	CreatedAt    string `json:"createdAt"`
}

type DeviceListItem struct {
	DeviceID   string `json:"deviceId"`
	DeviceName string `json:"deviceName"`
	ProductKey string `json:"productKey"`
	Status     int8   `json:"status"`
	Location   string `json:"location"`
	CreatedAt  string `json:"createdAt"`
}

type DeviceListReq struct {
	Page       int    `form:"page,default=1"`
	Size       int    `form:"size,default=20"`
	ProductKey string `form:"productKey,optional"`
	Status     int    `form:"status,default=-1"`
}

type DeviceListResp struct {
	Total int              `json:"total"`
	List  []DeviceListItem `json:"list"`
}

type DeviceRegisterReq struct {
	ProductKey string `json:"productKey"`
	DeviceName string `json:"deviceName,optional"`
	ParkID     string `json:"parkId,optional"`
	BuildingID string `json:"buildingId,optional"`
	Floor      string `json:"floor,optional"`
	Location   string `json:"location,optional"`
}

type DeviceRegisterResp struct {
	DeviceID     string `json:"deviceId"`
	DeviceSecret string `json:"deviceSecret"`
}

type DeviceStatusReq struct {
	DeviceID string `path:"id"`
	Status   int8   `json:"status"`
}

type PageReq struct {
	Page int `form:"page,default=1" json:"page"`
	Size int `form:"size,default=20" json:"size"`
}

type ProductCreateReq struct {
	ProductKey  string `json:"productKey"`
	ProductName string `json:"productName"`
	Description string `json:"description,optional"`
	ThingModel  string `json:"thingModel,optional"`
}

type ProductDetailReq struct {
	ProductKey string `path:"key"`
}

type ProductDetailResp struct {
	ProductKey  string `json:"productKey"`
	ProductName string `json:"productName"`
	Description string `json:"description"`
	ThingModel  string `json:"thingModel,optional"`
	Status      int8   `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type ProductListItem struct {
	ProductKey  string `json:"productKey"`
	ProductName string `json:"productName"`
	Status      int8   `json:"status"`
	CreatedAt   string `json:"createdAt"`
}

type ProductListReq struct {
	Page   int `form:"page,default=1"`
	Size   int `form:"size,default=20"`
	Status int `form:"status,default=-1"`
}

type ProductListResp struct {
	Total int               `json:"total"`
	List  []ProductListItem `json:"list"`
}

type ProductUpdateReq struct {
	ProductKey  string `path:"key"`
	ProductName string `json:"productName,optional"`
	Description string `json:"description,optional"`
	ThingModel  string `json:"thingModel,optional"`
}
