// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/access-control-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/access/grant",
				Handler: GrantAccessHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/access/revoke",
				Handler: RevokeAccessHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/access/remote-open",
				Handler: RemoteOpenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/access/records",
				Handler: ListAccessRecordsHandler(serverCtx),
			},
		},
	)
}
