// Code generated by goctl. DO NOT EDIT.
// 契约源: accesscontrol.api (P0 门禁基础逻辑: 记录列表查询 + 远程开门).
package handler

import (
	"net/http"

	"onepark/app/access-control-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/access/records",
				Handler: ListAccessRecordsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/access/remote-open",
				Handler: AccessRemoteOpenHandler(serverCtx),
			},
		},
	)
}
