// Code generated by goctl. DO NOT EDIT.
package types

type ListAlarmsReq struct {
	Level    int8   `form:"level,optional"`     // 告警等级筛选: 1提示 2一般 3严重 4紧急; 不传或<0表示全部
	Status   int8   `form:"status,optional"`    // 告警状态筛选: 0未处理 1已确认 2已解决; 不传或<0表示全部
	AreaId   int64  `form:"area_id,optional"`   // 区域ID筛选, 0表示全部
	DeviceId string `form:"device_id,optional"` // 设备ID筛选, 空表示全部
	Page     int64  `form:"page"`               // 页码(从1开始)
	PageSize int64  `form:"page_size"`          // 每页大小
}

type UpdateAlarmStatusReq struct {
	Id     int64  `path:"id"`              // 告警ID(路径参数)
	Action string `json:"action"`          // 动作: ack 确认 / resolve 解决
	Remark string `json:"remark,optional"` // 处理备注(如"已派安保现场核实")
}

type IdReq struct {
	Id int64 `path:"id"` // 告警主键ID(路径参数)
}

type AlarmItem struct {
	Id        int64  `json:"id"`
	AlarmNo   string `json:"alarm_no"`
	DeviceId  string `json:"device_id"`
	AreaId    int64  `json:"area_id"`
	EventType string `json:"event_type"`
	Level     int8   `json:"level"`
	Status    int8   `json:"status"`
	Content   string `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

type AlarmListResp struct {
	Total    int64       `json:"total"`
	Page     int64       `json:"page"`
	PageSize int64       `json:"page_size"`
	List     []AlarmItem `json:"list"`
}

type AlarmDetailResp struct {
	Id        int64  `json:"id"`
	TenantId  int64  `json:"tenant_id"`
	AlarmNo   string `json:"alarm_no"`
	RuleId    int64  `json:"rule_id"`
	DeviceId  string `json:"device_id"`
	AreaId    int64  `json:"area_id"`
	EventType string `json:"event_type"`
	Level     int8   `json:"level"`
	Status    int8   `json:"status"`
	Content   string `json:"content"`
	RequestId string `json:"request_id"`
	AckBy     int64  `json:"ack_by"`
	AckAt     int64  `json:"ack_at"`
	ResolveBy int64  `json:"resolve_by"`
	ResolveAt int64  `json:"resolve_at"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UpdateAlarmStatusResp struct {
	Id     int64 `json:"id"`
	Status int8  `json:"status"`
}
