// Code generated by goctl. DO NOT EDIT.
package types

// ListAlarmsReq 历史告警检索请求(#41: ES 检索 + 等级聚合), ES 不可用时降级 MySQL.
type ListAlarmsReq struct {
	StartTime int64  `form:"start_time,optional"` // 起始时间(秒级时间戳), 0或不传表示不限
	EndTime   int64  `form:"end_time,optional"`   // 结束时间(秒级时间戳), 0或不传表示不限
	Level     int8   `form:"level,optional"`      // 告警等级筛选: 1提示 2一般 3严重 4紧急; 不传或<0表示全部
	Status    int8   `form:"status,optional"`     // 告警状态: 0未处理 1已确认 2已解决; 不传即 0(只查未处理), 查全部状态请传负数
	AreaId    int64  `form:"area_id,optional"`    // 区域ID筛选, 0表示全部
	DeviceId  string `form:"device_id,optional"`  // 设备ID筛选, 空表示全部
	EventType string `form:"event_type,optional"` // 事件类型筛选, 空表示全部
	// Keyword 告警内容关键词全文检索(docs/m3/04 §7.1: content 建 ik 分词后用 ES match 命中).
	// 空表示不参与检索, 行为与新增该字段前完全一致.
	// ES 与 MySQL 两条路径都支持: ES 走 match(分词), MySQL 降级走 LIKE '%kw%'(子串),
	// 避免"ES 不可用时关键词被静默忽略、返回未过滤的全量"这种比报错更糟的静默错误.
	Keyword  string `form:"keyword,optional"`   // 告警内容关键词, 空表示不检索
	Page     int64  `form:"page,optional"`      // 页码(从1开始), 不传默认 1
	PageSize int64  `form:"page_size,optional"` // 每页大小, 不传默认 10, 上限 100
}

// ListActiveAlarmsReq 活跃告警列表请求(#38): 固定 status=0, 不接受状态入参.
type ListActiveAlarmsReq struct {
	Level    int8   `form:"level,optional"`     // 告警等级筛选: 1提示 2一般 3严重 4紧急; 不传或<0表示全部
	AreaId   int64  `form:"area_id,optional"`   // 区域ID筛选, 0表示全部
	DeviceId string `form:"device_id,optional"` // 设备ID筛选, 空表示全部
	Page     int64  `form:"page,optional"`      // 页码(从1开始), 不传默认 1
	PageSize int64  `form:"page_size,optional"` // 每页大小, 不传默认 10, 上限 100
}

type UpdateAlarmStatusReq struct {
	Id     int64  `path:"id"`              // 告警ID(路径参数)
	Action string `json:"action"`          // 动作: ack 确认 / resolve 解决
	Remark string `json:"remark,optional"` // 处理备注(如"已派安保现场核实")
}

// AlarmActionReq #39/#40 契约路径(确认/解决)专用入参: 动作由路径决定, 请求体只需备注。
//
// 刻意不与 UpdateAlarmStatusReq 共用 —— 后者的 action 是 json 必填字段(没有 ,optional),
// 而按 #39/#40 契约调用时 body 里本就不该出现 action(动作写在路径上), 复用会让这类请求
// 在参数校验阶段就被拒成 M3-W-1001「请求参数解析失败」。曾实测踩到, 勿合并回一个结构体。
type AlarmActionReq struct {
	Id     int64  `path:"id"`              // 告警ID(路径参数)
	Remark string `json:"remark,optional"` // 处理备注(如"已派安保现场核实")
}

type IdReq struct {
	Id int64 `path:"id"` // 告警主键ID(路径参数)
}

type AlarmItem struct {
	Id        int64  `json:"id"`
	AlarmNo   string `json:"alarm_no"`
	DeviceId  string `json:"device_id"`
	AreaId    int64  `json:"area_id"`
	EventType string `json:"event_type"`
	Level     int8   `json:"level"`
	Status    int8   `json:"status"`
	Content   string `json:"content"`
	CreatedAt int64  `json:"created_at"`
}

// AlarmLevelAgg 历史告警按等级的分布聚合(#41).
type AlarmLevelAgg struct {
	LevelCount map[string]int64 `json:"level_count"` // 等级 -> 条数, 如 {"3":5,"4":2}
}

// AlarmListResp 告警分页列表响应.
// Aggs 仅在 #41 历史检索时返回; 活跃告警列表(#38)为 nil.
// 用 omitempty 而不是 goctl 的 ,optional: 后者只做校验, 序列化时仍会输出 "aggs":null,
// 前端就得多写一层判空(真机抓包时发现)。
type AlarmListResp struct {
	Total    int64          `json:"total"`
	Page     int64          `json:"page"`
	PageSize int64          `json:"page_size"`
	List     []AlarmItem    `json:"list"`
	Aggs     *AlarmLevelAgg `json:"aggs,omitempty"`
}

type AlarmDetailResp struct {
	Id        int64  `json:"id"`
	TenantId  int64  `json:"tenant_id"`
	AlarmNo   string `json:"alarm_no"`
	RuleId    int64  `json:"rule_id"`
	DeviceId  string `json:"device_id"`
	AreaId    int64  `json:"area_id"`
	EventType string `json:"event_type"`
	Level     int8   `json:"level"`
	Status    int8   `json:"status"`
	Content   string `json:"content"`
	RequestId string `json:"request_id"`
	AckBy     int64  `json:"ack_by"`
	AckAt     int64  `json:"ack_at"`
	ResolveBy int64  `json:"resolve_by"`
	ResolveAt int64  `json:"resolve_at"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UpdateAlarmStatusResp struct {
	Id     int64 `json:"id"`
	Status int8  `json:"status"`
}

// CreateRuleReq 创建告警规则请求(docs/m3/04 #34)
// DeviceType + EventType 构成「按设备类型 + 事件类型映射告警等级」的配置面, 均可留空(表示不限).
type CreateRuleReq struct {
	Name          string `json:"name"`
	DeviceType    string `json:"device_type,optional"`
	DeviceId      string `json:"device_id,optional"`
	AreaId        int64  `json:"area_id,optional"`
	EventType     string `json:"event_type"`
	Level         int8   `json:"level"`
	RuleType      string `json:"rule_type"`
	Conditions    string `json:"conditions"`
	WindowSeconds int    `json:"window_seconds,optional"`
	Status        int8   `json:"status"`
}

type CreateRuleResp struct {
	Id int64 `json:"id"`
}

// UpdateRuleReq 更新规则请求(#35): 字段可选, 传什么改什么.
// Level/Status 用指针: 0 是有效取值(status=0 即禁用), 用零值判断"是否传入"会误禁用规则.
type UpdateRuleReq struct {
	Id            int64  `path:"id"`
	Name          string `json:"name,optional"`
	DeviceType    string `json:"device_type,optional"`
	DeviceId      string `json:"device_id,optional"`
	AreaId        int64  `json:"area_id,optional"`
	EventType     string `json:"event_type,optional"`
	Level         *int8  `json:"level,optional"`
	RuleType      string `json:"rule_type,optional"`
	Conditions    string `json:"conditions,optional"`
	WindowSeconds int    `json:"window_seconds,optional"`
	Status        *int8  `json:"status,optional"`
}

type UpdateRuleResp struct {
	Id int64 `json:"id"`
}

type RuleItem struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	DeviceType    string `json:"device_type"`
	DeviceId      string `json:"device_id"`
	AreaId        int64  `json:"area_id"`
	EventType     string `json:"event_type"`
	Level         int8   `json:"level"`
	RuleType      string `json:"rule_type"`
	Conditions    string `json:"conditions"`
	WindowSeconds int    `json:"window_seconds"`
	Status        int8   `json:"status"`
	CreatedAt     int64  `json:"created_at"`
	UpdatedAt     int64  `json:"updated_at"`
}

// RuleDetailResp 规则详情响应(#36)
type RuleDetailResp struct {
	RuleItem
}

// ListRulesReq 规则分页列表请求(#37)
type ListRulesReq struct {
	DeviceType string `form:"device_type,optional"`
	DeviceId   string `form:"device_id,optional"`
	EventType  string `form:"event_type,optional"`
	Status     int8   `form:"status,optional"`
	Page       int64  `form:"page"`
	PageSize   int64  `form:"page_size"`
}

type ListRulesResp struct {
	Total    int64      `json:"total"`
	Page     int64      `json:"page"`
	PageSize int64      `json:"page_size"`
	List     []RuleItem `json:"list"`
}

// ListDLQReq 死信台账列表请求(docs/m3/06 §5.4 可查/可重放).
type ListDLQReq struct {
	Status   int8   `form:"status,optional"` // 死信状态: 0待处理 1已重放 2已丢弃; 不传或<0表示全部
	DeviceId string `form:"device_id,optional"`
	Page     int64  `form:"page,optional"`
	PageSize int64  `form:"page_size,optional"`
}

// DLQItem 死信台账条目; Payload 为原始报文, 供运维定位与重放.
type DLQItem struct {
	Id          int64  `json:"id"`
	Topic       string `json:"topic"`
	PartitionNo int    `json:"partition_no"`
	MsgOffset   int64  `json:"msg_offset"`
	RequestId   string `json:"request_id"`
	DeviceId    string `json:"device_id"`
	EventType   string `json:"event_type"`
	Payload     string `json:"payload"`
	ErrorMsg    string `json:"error_msg"`
	RetryCount  int    `json:"retry_count"`
	Status      int8   `json:"status"`
	CreatedAt   int64  `json:"created_at"`
}

type ListDLQResp struct {
	Total    int64     `json:"total"`
	Page     int64     `json:"page"`
	PageSize int64     `json:"page_size"`
	List     []DLQItem `json:"list"`
}

// ReplayDLQResp 死信重放结果.
// Replayed 为 false 表示主链路仍未处理成功(台账状态保持待处理), 便于运维判断是否继续重试.
type ReplayDLQResp struct {
	Id       int64 `json:"id"`
	Replayed bool  `json:"replayed"`
}
