// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	dispatch "onepark/app/dispatch-service/internal/handler/dispatch"
	"onepark/app/dispatch-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/dispatch",
				Handler: dispatch.TaskCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dispatch/:id",
				Handler: dispatch.TaskDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/dispatch/:id/assign",
				Handler: dispatch.TaskAssignHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/dispatch/:id/status",
				Handler: dispatch.TaskStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/dispatches",
				Handler: dispatch.TaskListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
