// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: billing/billing.proto

package billingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "onepark/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingService_Ping_FullMethodName          = "/onepark.billing.BillingService/Ping"
	BillingService_GetBillRules_FullMethodName  = "/onepark.billing.BillingService/GetBillRules"
	BillingService_GetBills_FullMethodName      = "/onepark.billing.BillingService/GetBills"
	BillingService_CalculateBill_FullMethodName = "/onepark.billing.BillingService/CalculateBill"
)

// BillingServiceClient is the client API for BillingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BillingServiceClient interface {
	Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
	// 计费规则列表(对应 HTTP GET /api/billing/rules)
	GetBillRules(ctx context.Context, in *GetBillRulesRequest, opts ...grpc.CallOption) (*GetBillRulesResponse, error)
	// 账单列表(对应 HTTP GET /api/billing/bills)
	GetBills(ctx context.Context, in *GetBillsRequest, opts ...grpc.CallOption) (*GetBillsResponse, error)
	// 按区域+账期生成账单(对应 HTTP POST /api/billing/generate)
	CalculateBill(ctx context.Context, in *CalculateBillRequest, opts ...grpc.CallOption) (*CalculateBillResponse, error)
}

type billingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingServiceClient(cc grpc.ClientConnInterface) BillingServiceClient {
	return &billingServiceClient{cc}
}

func (c *billingServiceClient) Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, BillingService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetBillRules(ctx context.Context, in *GetBillRulesRequest, opts ...grpc.CallOption) (*GetBillRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBillRulesResponse)
	err := c.cc.Invoke(ctx, BillingService_GetBillRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) GetBills(ctx context.Context, in *GetBillsRequest, opts ...grpc.CallOption) (*GetBillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBillsResponse)
	err := c.cc.Invoke(ctx, BillingService_GetBills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingServiceClient) CalculateBill(ctx context.Context, in *CalculateBillRequest, opts ...grpc.CallOption) (*CalculateBillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateBillResponse)
	err := c.cc.Invoke(ctx, BillingService_CalculateBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingServiceServer is the server API for BillingService service.
// All implementations must embed UnimplementedBillingServiceServer
// for forward compatibility.
type BillingServiceServer interface {
	Ping(context.Context, *common.Empty) (*common.Empty, error)
	// 计费规则列表(对应 HTTP GET /api/billing/rules)
	GetBillRules(context.Context, *GetBillRulesRequest) (*GetBillRulesResponse, error)
	// 账单列表(对应 HTTP GET /api/billing/bills)
	GetBills(context.Context, *GetBillsRequest) (*GetBillsResponse, error)
	// 按区域+账期生成账单(对应 HTTP POST /api/billing/generate)
	CalculateBill(context.Context, *CalculateBillRequest) (*CalculateBillResponse, error)
	mustEmbedUnimplementedBillingServiceServer()
}

// UnimplementedBillingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingServiceServer struct{}

func (UnimplementedBillingServiceServer) Ping(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBillingServiceServer) GetBillRules(context.Context, *GetBillRulesRequest) (*GetBillRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBillRules not implemented")
}
func (UnimplementedBillingServiceServer) GetBills(context.Context, *GetBillsRequest) (*GetBillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBills not implemented")
}
func (UnimplementedBillingServiceServer) CalculateBill(context.Context, *CalculateBillRequest) (*CalculateBillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateBill not implemented")
}
func (UnimplementedBillingServiceServer) mustEmbedUnimplementedBillingServiceServer() {}
func (UnimplementedBillingServiceServer) testEmbeddedByValue()                        {}

// UnsafeBillingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingServiceServer will
// result in compilation errors.
type UnsafeBillingServiceServer interface {
	mustEmbedUnimplementedBillingServiceServer()
}

func RegisterBillingServiceServer(s grpc.ServiceRegistrar, srv BillingServiceServer) {
	// If the following call panics, it indicates UnimplementedBillingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingService_ServiceDesc, srv)
}

func _BillingService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).Ping(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetBillRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBillRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetBillRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBillRules(ctx, req.(*GetBillRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_GetBills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).GetBills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_GetBills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).GetBills(ctx, req.(*GetBillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingService_CalculateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingServiceServer).CalculateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingService_CalculateBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingServiceServer).CalculateBill(ctx, req.(*CalculateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingService_ServiceDesc is the grpc.ServiceDesc for BillingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepark.billing.BillingService",
	HandlerType: (*BillingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BillingService_Ping_Handler,
		},
		{
			MethodName: "GetBillRules",
			Handler:    _BillingService_GetBillRules_Handler,
		},
		{
			MethodName: "GetBills",
			Handler:    _BillingService_GetBills_Handler,
		},
		{
			MethodName: "CalculateBill",
			Handler:    _BillingService_CalculateBill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing/billing.proto",
}
