// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: billing/billing.proto

package billingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "onepark/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBillRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 1启用 0停用, 不传查全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillRulesRequest) Reset() {
	*x = GetBillRulesRequest{}
	mi := &file_billing_billing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillRulesRequest) ProtoMessage() {}

func (x *GetBillRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillRulesRequest.ProtoReflect.Descriptor instead.
func (*GetBillRulesRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{0}
}

func (x *GetBillRulesRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *GetBillRulesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BillRuleItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ZoneId        string                 `protobuf:"bytes,3,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	RuleType      int64                  `protobuf:"varint,4,opt,name=ruleType,proto3" json:"ruleType,omitempty"`
	Config        string                 `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"` // RuleConfig 的 JSON 字符串
	Status        int64                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillRuleItem) Reset() {
	*x = BillRuleItem{}
	mi := &file_billing_billing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillRuleItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillRuleItem) ProtoMessage() {}

func (x *BillRuleItem) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillRuleItem.ProtoReflect.Descriptor instead.
func (*BillRuleItem) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{1}
}

func (x *BillRuleItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BillRuleItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BillRuleItem) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *BillRuleItem) GetRuleType() int64 {
	if x != nil {
		return x.RuleType
	}
	return 0
}

func (x *BillRuleItem) GetConfig() string {
	if x != nil {
		return x.Config
	}
	return ""
}

func (x *BillRuleItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BillRuleItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetBillRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List          []*BillRuleItem        `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillRulesResponse) Reset() {
	*x = GetBillRulesResponse{}
	mi := &file_billing_billing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillRulesResponse) ProtoMessage() {}

func (x *GetBillRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillRulesResponse.ProtoReflect.Descriptor instead.
func (*GetBillRulesResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillRulesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetBillRulesResponse) GetList() []*BillRuleItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetBillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 1待缴 2已缴 3作废
	Page          int64                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillsRequest) Reset() {
	*x = GetBillsRequest{}
	mi := &file_billing_billing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillsRequest) ProtoMessage() {}

func (x *GetBillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillsRequest.ProtoReflect.Descriptor instead.
func (*GetBillsRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{3}
}

func (x *GetBillsRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *GetBillsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBillsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBillsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type BillItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BillNo        string                 `protobuf:"bytes,1,opt,name=billNo,proto3" json:"billNo,omitempty"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	RuleId        int64                  `protobuf:"varint,3,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	PeriodStart   string                 `protobuf:"bytes,4,opt,name=periodStart,proto3" json:"periodStart,omitempty"`
	PeriodEnd     string                 `protobuf:"bytes,5,opt,name=periodEnd,proto3" json:"periodEnd,omitempty"`
	UsageKwh      float64                `protobuf:"fixed64,6,opt,name=usageKwh,proto3" json:"usageKwh,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        int64                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillItem) Reset() {
	*x = BillItem{}
	mi := &file_billing_billing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillItem) ProtoMessage() {}

func (x *BillItem) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillItem.ProtoReflect.Descriptor instead.
func (*BillItem) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{4}
}

func (x *BillItem) GetBillNo() string {
	if x != nil {
		return x.BillNo
	}
	return ""
}

func (x *BillItem) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *BillItem) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *BillItem) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *BillItem) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *BillItem) GetUsageKwh() float64 {
	if x != nil {
		return x.UsageKwh
	}
	return 0
}

func (x *BillItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillItem) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BillItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetBillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int64                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	List          []*BillItem            `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillsResponse) Reset() {
	*x = GetBillsResponse{}
	mi := &file_billing_billing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillsResponse) ProtoMessage() {}

func (x *GetBillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillsResponse.ProtoReflect.Descriptor instead.
func (*GetBillsResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{5}
}

func (x *GetBillsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetBillsResponse) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBillsResponse) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetBillsResponse) GetList() []*BillItem {
	if x != nil {
		return x.List
	}
	return nil
}

type CalculateBillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`  // 账期, 如 2026-09; 不传默认本月
	RuleId        int64                  `protobuf:"varint,3,opt,name=ruleId,proto3" json:"ruleId,omitempty"` // 指定规则; 不传自动选区域/全园区启用规则
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateBillRequest) Reset() {
	*x = CalculateBillRequest{}
	mi := &file_billing_billing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateBillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateBillRequest) ProtoMessage() {}

func (x *CalculateBillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateBillRequest.ProtoReflect.Descriptor instead.
func (*CalculateBillRequest) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{6}
}

func (x *CalculateBillRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *CalculateBillRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *CalculateBillRequest) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type BillDetailItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Usage         float64                `protobuf:"fixed64,2,opt,name=usage,proto3" json:"usage,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillDetailItem) Reset() {
	*x = BillDetailItem{}
	mi := &file_billing_billing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillDetailItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillDetailItem) ProtoMessage() {}

func (x *BillDetailItem) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillDetailItem.ProtoReflect.Descriptor instead.
func (*BillDetailItem) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{7}
}

func (x *BillDetailItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BillDetailItem) GetUsage() float64 {
	if x != nil {
		return x.Usage
	}
	return 0
}

func (x *BillDetailItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BillDetailItem) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CalculateBillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BillNo        string                 `protobuf:"bytes,1,opt,name=billNo,proto3" json:"billNo,omitempty"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	PeriodStart   string                 `protobuf:"bytes,3,opt,name=periodStart,proto3" json:"periodStart,omitempty"`
	PeriodEnd     string                 `protobuf:"bytes,4,opt,name=periodEnd,proto3" json:"periodEnd,omitempty"`
	RuleId        int64                  `protobuf:"varint,5,opt,name=ruleId,proto3" json:"ruleId,omitempty"`
	RuleName      string                 `protobuf:"bytes,6,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	UsageKwh      float64                `protobuf:"fixed64,7,opt,name=usageKwh,proto3" json:"usageKwh,omitempty"`
	Amount        float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Detail        []*BillDetailItem      `protobuf:"bytes,9,rep,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateBillResponse) Reset() {
	*x = CalculateBillResponse{}
	mi := &file_billing_billing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateBillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateBillResponse) ProtoMessage() {}

func (x *CalculateBillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_billing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateBillResponse.ProtoReflect.Descriptor instead.
func (*CalculateBillResponse) Descriptor() ([]byte, []int) {
	return file_billing_billing_proto_rawDescGZIP(), []int{8}
}

func (x *CalculateBillResponse) GetBillNo() string {
	if x != nil {
		return x.BillNo
	}
	return ""
}

func (x *CalculateBillResponse) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *CalculateBillResponse) GetPeriodStart() string {
	if x != nil {
		return x.PeriodStart
	}
	return ""
}

func (x *CalculateBillResponse) GetPeriodEnd() string {
	if x != nil {
		return x.PeriodEnd
	}
	return ""
}

func (x *CalculateBillResponse) GetRuleId() int64 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

func (x *CalculateBillResponse) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *CalculateBillResponse) GetUsageKwh() float64 {
	if x != nil {
		return x.UsageKwh
	}
	return 0
}

func (x *CalculateBillResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalculateBillResponse) GetDetail() []*BillDetailItem {
	if x != nil {
		return x.Detail
	}
	return nil
}

var File_billing_billing_proto protoreflect.FileDescriptor

const file_billing_billing_proto_rawDesc = "" +
	"\n" +
	"\x15billing/billing.proto\x12\x0fonepark.billing\x1a\x13common/common.proto\"E\n" +
	"\x13GetBillRulesRequest\x12\x16\n" +
	"\x06zoneId\x18\x01 \x01(\tR\x06zoneId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xb4\x01\n" +
	"\fBillRuleItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06zoneId\x18\x03 \x01(\tR\x06zoneId\x12\x1a\n" +
	"\bruleType\x18\x04 \x01(\x03R\bruleType\x12\x16\n" +
	"\x06config\x18\x05 \x01(\tR\x06config\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x03R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\"_\n" +
	"\x14GetBillRulesResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x121\n" +
	"\x04list\x18\x02 \x03(\v2\x1d.onepark.billing.BillRuleItemR\x04list\"q\n" +
	"\x0fGetBillsRequest\x12\x16\n" +
	"\x06zoneId\x18\x01 \x01(\tR\x06zoneId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\xfc\x01\n" +
	"\bBillItem\x12\x16\n" +
	"\x06billNo\x18\x01 \x01(\tR\x06billNo\x12\x16\n" +
	"\x06zoneId\x18\x02 \x01(\tR\x06zoneId\x12\x16\n" +
	"\x06ruleId\x18\x03 \x01(\x03R\x06ruleId\x12 \n" +
	"\vperiodStart\x18\x04 \x01(\tR\vperiodStart\x12\x1c\n" +
	"\tperiodEnd\x18\x05 \x01(\tR\tperiodEnd\x12\x1a\n" +
	"\busageKwh\x18\x06 \x01(\x01R\busageKwh\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12\x16\n" +
	"\x06status\x18\b \x01(\x03R\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\t \x01(\tR\tcreatedAt\"\x87\x01\n" +
	"\x10GetBillsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x03R\x04page\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12-\n" +
	"\x04list\x18\x04 \x03(\v2\x19.onepark.billing.BillItemR\x04list\"^\n" +
	"\x14CalculateBillRequest\x12\x16\n" +
	"\x06zoneId\x18\x01 \x01(\tR\x06zoneId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12\x16\n" +
	"\x06ruleId\x18\x03 \x01(\x03R\x06ruleId\"h\n" +
	"\x0eBillDetailItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05usage\x18\x02 \x01(\x01R\x05usage\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"\xa8\x02\n" +
	"\x15CalculateBillResponse\x12\x16\n" +
	"\x06billNo\x18\x01 \x01(\tR\x06billNo\x12\x16\n" +
	"\x06zoneId\x18\x02 \x01(\tR\x06zoneId\x12 \n" +
	"\vperiodStart\x18\x03 \x01(\tR\vperiodStart\x12\x1c\n" +
	"\tperiodEnd\x18\x04 \x01(\tR\tperiodEnd\x12\x16\n" +
	"\x06ruleId\x18\x05 \x01(\x03R\x06ruleId\x12\x1a\n" +
	"\bruleName\x18\x06 \x01(\tR\bruleName\x12\x1a\n" +
	"\busageKwh\x18\a \x01(\x01R\busageKwh\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x127\n" +
	"\x06detail\x18\t \x03(\v2\x1f.onepark.billing.BillDetailItemR\x06detail2\xd4\x02\n" +
	"\x0eBillingService\x124\n" +
	"\x04Ping\x12\x15.onepark.common.Empty\x1a\x15.onepark.common.Empty\x12[\n" +
	"\fGetBillRules\x12$.onepark.billing.GetBillRulesRequest\x1a%.onepark.billing.GetBillRulesResponse\x12O\n" +
	"\bGetBills\x12 .onepark.billing.GetBillsRequest\x1a!.onepark.billing.GetBillsResponse\x12^\n" +
	"\rCalculateBill\x12%.onepark.billing.CalculateBillRequest\x1a&.onepark.billing.CalculateBillResponseB!Z\x1fonepark/proto/billing;billingpbb\x06proto3"

var (
	file_billing_billing_proto_rawDescOnce sync.Once
	file_billing_billing_proto_rawDescData []byte
)

func file_billing_billing_proto_rawDescGZIP() []byte {
	file_billing_billing_proto_rawDescOnce.Do(func() {
		file_billing_billing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)))
	})
	return file_billing_billing_proto_rawDescData
}

var file_billing_billing_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_billing_billing_proto_goTypes = []any{
	(*GetBillRulesRequest)(nil),   // 0: onepark.billing.GetBillRulesRequest
	(*BillRuleItem)(nil),          // 1: onepark.billing.BillRuleItem
	(*GetBillRulesResponse)(nil),  // 2: onepark.billing.GetBillRulesResponse
	(*GetBillsRequest)(nil),       // 3: onepark.billing.GetBillsRequest
	(*BillItem)(nil),              // 4: onepark.billing.BillItem
	(*GetBillsResponse)(nil),      // 5: onepark.billing.GetBillsResponse
	(*CalculateBillRequest)(nil),  // 6: onepark.billing.CalculateBillRequest
	(*BillDetailItem)(nil),        // 7: onepark.billing.BillDetailItem
	(*CalculateBillResponse)(nil), // 8: onepark.billing.CalculateBillResponse
	(*common.Empty)(nil),          // 9: onepark.common.Empty
}
var file_billing_billing_proto_depIdxs = []int32{
	1, // 0: onepark.billing.GetBillRulesResponse.list:type_name -> onepark.billing.BillRuleItem
	4, // 1: onepark.billing.GetBillsResponse.list:type_name -> onepark.billing.BillItem
	7, // 2: onepark.billing.CalculateBillResponse.detail:type_name -> onepark.billing.BillDetailItem
	9, // 3: onepark.billing.BillingService.Ping:input_type -> onepark.common.Empty
	0, // 4: onepark.billing.BillingService.GetBillRules:input_type -> onepark.billing.GetBillRulesRequest
	3, // 5: onepark.billing.BillingService.GetBills:input_type -> onepark.billing.GetBillsRequest
	6, // 6: onepark.billing.BillingService.CalculateBill:input_type -> onepark.billing.CalculateBillRequest
	9, // 7: onepark.billing.BillingService.Ping:output_type -> onepark.common.Empty
	2, // 8: onepark.billing.BillingService.GetBillRules:output_type -> onepark.billing.GetBillRulesResponse
	5, // 9: onepark.billing.BillingService.GetBills:output_type -> onepark.billing.GetBillsResponse
	8, // 10: onepark.billing.BillingService.CalculateBill:output_type -> onepark.billing.CalculateBillResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_billing_billing_proto_init() }
func file_billing_billing_proto_init() {
	if File_billing_billing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_billing_proto_rawDesc), len(file_billing_billing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_billing_proto_goTypes,
		DependencyIndexes: file_billing_billing_proto_depIdxs,
		MessageInfos:      file_billing_billing_proto_msgTypes,
	}.Build()
	File_billing_billing_proto = out.File
	file_billing_billing_proto_goTypes = nil
	file_billing_billing_proto_depIdxs = nil
}
