// Code generated by goctl. DO NOT EDIT.
package types

type HistoryPoint struct {
	Time  string  `json:"time"`  // 时间点, 如 2026-09-15 09:00
	Usage float64 `json:"usage"` // 该时间段的用量(度) = MAX读数 - MIN读数
}

type HistoryRequest struct {
	DeviceId    string `form:"deviceId"`
	Start       string `form:"start,optional"`       // 开始时间, 不传默认今天 0 点
	End         string `form:"end,optional"`         // 结束时间, 不传默认明天 0 点
	Granularity string `form:"granularity,optional"` // hour | day
}

type HistoryResponse struct {
	DeviceId   string         `json:"deviceId"`
	Points     []HistoryPoint `json:"points"`
	TotalUsage float64        `json:"totalUsage"` // 整个区间的总用量
}

type RealtimeRequest struct {
	DeviceId string `path:"deviceId"`
}

type RealtimeResponse struct {
	DeviceId   string  `json:"deviceId"`
	ZoneId     string  `json:"zoneId"`
	EnergyKwh  float64 `json:"energyKwh"`  // 电表累计读数
	PowerKw    float64 `json:"powerKw"`    // 瞬时功率, 可能为 0
	ReportedAt string  `json:"reportedAt"` // 采集时间
	TodayUsage float64 `json:"todayUsage"` // 今日用量 = 今日最后一条 - 今日第一条
}
