// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"onepark/app/leasing-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/contracts",
				Handler: ListLeaseContractsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/leasing"),
	)
}
