// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	lease "onepark/app/leasing-service/internal/handler/lease"
	"onepark/app/leasing-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/bill/:id/status",
				Handler: lease.BillStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bill/auto",
				Handler: lease.BillAutoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bills",
				Handler: lease.BillListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/bills/summary",
				Handler: lease.BillSummaryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/contract",
				Handler: lease.ContractCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/contract/:id",
				Handler: lease.ContractDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/contract/:id",
				Handler: lease.ContractUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/contracts",
				Handler: lease.ContractListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/contracts/expiring",
				Handler: lease.ContractExpiringHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/occupancy",
				Handler: lease.OccupancyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/zone",
				Handler: lease.ZoneUpsertHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/zones",
				Handler: lease.ZoneListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/lease"),
	)
}
