// Code generated by goctl. DO NOT EDIT.
package types

// TimeWindow 时间段权限(docs/m3/04 #45)
type TimeWindow struct {
	Start string  `json:"start"`
	End   string  `json:"end"`
	Days  []int64 `json:"days"`
}

// RemoteOpenReq 远程开门请求(docs/m3/04 #47)
type RemoteOpenReq struct {
	DeviceId  string `json:"device_id"`
	Reason    string `json:"reason,optional"`
	RequestId string `json:"request_id,optional"`
}

// RemoteOpenResp 远程开门响应
type RemoteOpenResp struct {
	Success  bool   `json:"success"`
	DeviceId string `json:"device_id"`
	Message  string `json:"message"`
}

// GrantAccessReq 门禁授权请求(支持批量: 人员 × 设备)
type GrantAccessReq struct {
	PersonIds  []int64     `json:"person_ids"`
	DeviceIds  []string    `json:"device_ids"`
	TimeWindow *TimeWindow `json:"time_window,optional"`
	Whitelist  bool        `json:"whitelist,optional"`
	ExpireAt   string      `json:"expire_at,optional"`
}

// GrantAccessResp 门禁授权响应
type GrantAccessResp struct {
	Granted int64 `json:"granted"`
}

// RevokeAccessReq 门禁撤权请求
type RevokeAccessReq struct {
	PersonIds []int64  `json:"person_ids"`
	DeviceIds []string `json:"device_ids"`
}

// RevokeAccessResp 门禁撤权响应
type RevokeAccessResp struct {
	Revoked int64 `json:"revoked"`
}

// AccessRecordItem 通行记录列表项
type AccessRecordItem struct {
	Id         int64  `json:"id"`
	PersonId   int64  `json:"person_id"`
	DeviceId   string `json:"device_id"`
	Result     int8   `json:"result"`
	OpenType   string `json:"open_type"`
	FailReason string `json:"fail_reason"`
	CreatedAt  int64  `json:"created_at"`
}

// ListAccessRecordsReq 通行记录查询请求
type ListAccessRecordsReq struct {
	PersonId  int64  `form:"person_id,optional"`
	DeviceId  string `form:"device_id,optional"`
	Result    int8   `form:"result,optional"`
	OpenType  string `form:"open_type,optional"`
	StartTime int64  `form:"start_time,optional"`
	EndTime   int64  `form:"end_time,optional"`
	Page      int64  `form:"page"`
	PageSize  int64  `form:"page_size"`
}

// ListAccessRecordsResp 通行记录分页响应
type ListAccessRecordsResp struct {
	Total    int64              `json:"total"`
	Page     int64              `json:"page"`
	PageSize int64              `json:"page_size"`
	List     []AccessRecordItem `json:"list"`
}
