// Code generated by goctl. DO NOT EDIT.
// 契约源: accesscontrol.api (门禁记录列表查询 + 远程开门).
package types

// AccessRemoteOpenReq 远程开门请求(指定门禁/道闸点位).
type AccessRemoteOpenReq struct {
	GateID int64  `json:"gate_id"`         // 门禁点位ID(parking_gate.id), 必填
	Remark string `json:"remark,optional"` // 开门事由
}

// AccessRemoteOpenResp 远程开门响应.
type AccessRemoteOpenResp struct {
	RecordID int64  `json:"record_id"` // 通行记录ID(access_record.id)
	GateID   int64  `json:"gate_id"`   // 门禁点位ID
	DeviceID string `json:"device_id"` // 实际执行开门的 M1 设备ID
}

// ListAccessRecordsReq 门禁通行记录分页查询请求.
type ListAccessRecordsReq struct {
	GateID   int64 `form:"gate_id,optional"` // 按点位过滤, 0 表示全部点位
	Page     int64 `form:"page"`
	PageSize int64 `form:"page_size"`
}

// AccessRecordItem 通行记录列表项.
type AccessRecordItem struct {
	Id         int64  `json:"id"`
	GateID     int64  `json:"gate_id"`
	DeviceID   string `json:"device_id,optional"` // 实际执行指令的设备
	Action     string `json:"action"`             // remote_open 远程开门
	Result     int8   `json:"result"`             // 1成功 0失败
	OperatorID int64  `json:"operator_id"`        // 操作人, 0=系统
	Remark     string `json:"remark,optional"`
	CreatedAt  int64  `json:"created_at"` // 秒级时间戳
}

// AccessRecordListResp 通行记录分页响应.
type AccessRecordListResp struct {
	Total int64              `json:"total"`
	List  []AccessRecordItem `json:"list"`
}
