// Code generated by goctl. DO NOT EDIT.
package types

type DailyRequest struct {
	Date string `form:"date,optional"`
}

type DailyResponse struct {
	Date        string      `json:"date"`
	TotalUsage  float64     `json:"totalUsage"` // 全园区当天总用量
	DeviceCount int64       `json:"deviceCount"`
	Zones       []ZoneUsage `json:"zones"` // 按用量从高到低排
}

type DayUsage struct {
	Date  string  `json:"date"`
	Usage float64 `json:"usage"`
}

type DeviceUsage struct {
	DeviceId       string  `json:"deviceId"`
	Usage          float64 `json:"usage"`
	Percent        float64 `json:"percent"`        // 占该区域总用量的百分比
	LastReading    float64 `json:"lastReading"`    // 区间内最后一次的累计读数
	LastReportedAt string  `json:"lastReportedAt"` // 最后一次读数的时间
}

type MonthlyRequest struct {
	Month string `form:"month,optional"`
}

type MonthlyResponse struct {
	Month          string     `json:"month"`
	TotalUsage     float64    `json:"totalUsage"`     // 本月总用量
	AvgDailyUsage  float64    `json:"avgDailyUsage"`  // 日均用量
	Days           []DayUsage `json:"days"`           // 每天一条, 没数据的日子不出现
	LastYearUsage  *float64   `json:"lastYearUsage"`  // 去年同月用量, 没有历史数据则为 null
	LastMonthUsage *float64   `json:"lastMonthUsage"` // 上月用量, 没有则为 null
	Yoy            *float64   `json:"yoy"`            // 同比 = (本月-去年同月)/去年同月, 小数形式
	Mom            *float64   `json:"mom"`            // 环比 = (本月-上月)/上月
}

type ZoneDetailRequest struct {
	ZoneId string `form:"zoneId"`
	Start  string `form:"start,optional"` // 不传默认今天 0 点
	End    string `form:"end,optional"`   // 不传默认明天 0 点
}

type ZoneDetailResponse struct {
	ZoneId      string        `json:"zoneId"`
	Start       string        `json:"start"`
	End         string        `json:"end"`
	TotalUsage  float64       `json:"totalUsage"`
	DeviceCount int64         `json:"deviceCount"`
	Devices     []DeviceUsage `json:"devices"` // 按用量从高到低排
	Days        []DayUsage    `json:"days"`    // 按天趋势, 给前端画柱状图
}

type ZoneUsage struct {
	ZoneId      string  `json:"zoneId"`
	Usage       float64 `json:"usage"`       // 该区域当天用量(度)
	DeviceCount int64   `json:"deviceCount"` // 该区域有数据的设备数
	Percent     float64 `json:"percent"`     // 占全园区用量的百分比, 如 20 表示 20%
}
