// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: shadow/shadow.proto

package shadow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ping string `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetPing() string {
	if x != nil {
		return x.Ping
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pong string `protobuf:"bytes,1,opt,name=pong,proto3" json:"pong,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetPong() string {
	if x != nil {
		return x.Pong
	}
	return ""
}

// GetShadowReq 查询影子请求
type GetShadowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备ID
}

func (x *GetShadowReq) Reset() {
	*x = GetShadowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShadowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShadowReq) ProtoMessage() {}

func (x *GetShadowReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShadowReq.ProtoReflect.Descriptor instead.
func (*GetShadowReq) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{2}
}

func (x *GetShadowReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// GetShadowResp 影子详情
type GetShadowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备ID
	Desired  []byte `protobuf:"bytes,2,opt,name=desired,proto3" json:"desired,omitempty"`                   // 期望值 JSON
	Reported []byte `protobuf:"bytes,3,opt,name=reported,proto3" json:"reported,omitempty"`                 // 上报值 JSON
	Version  uint32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                  // 当前版本号
}

func (x *GetShadowResp) Reset() {
	*x = GetShadowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShadowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShadowResp) ProtoMessage() {}

func (x *GetShadowResp) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShadowResp.ProtoReflect.Descriptor instead.
func (*GetShadowResp) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{3}
}

func (x *GetShadowResp) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetShadowResp) GetDesired() []byte {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *GetShadowResp) GetReported() []byte {
	if x != nil {
		return x.Reported
	}
	return nil
}

func (x *GetShadowResp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// UpdateDesiredReq 更新期望值请求
type UpdateDesiredReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备ID
	Desired  []byte `protobuf:"bytes,2,opt,name=desired,proto3" json:"desired,omitempty"`                   // 期望值 JSON
	Version  uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                  // 期望的当前版本号(乐观锁), 0 表示不校验
}

func (x *UpdateDesiredReq) Reset() {
	*x = UpdateDesiredReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDesiredReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDesiredReq) ProtoMessage() {}

func (x *UpdateDesiredReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDesiredReq.ProtoReflect.Descriptor instead.
func (*UpdateDesiredReq) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateDesiredReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpdateDesiredReq) GetDesired() []byte {
	if x != nil {
		return x.Desired
	}
	return nil
}

func (x *UpdateDesiredReq) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// UpdateReportedReq 更新上报值请求
type UpdateReportedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备ID
	Reported []byte `protobuf:"bytes,2,opt,name=reported,proto3" json:"reported,omitempty"`                 // 上报值 JSON
	Version  uint32 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`                  // 期望的当前版本号(乐观锁), 0 表示不校验
}

func (x *UpdateReportedReq) Reset() {
	*x = UpdateReportedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateReportedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateReportedReq) ProtoMessage() {}

func (x *UpdateReportedReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateReportedReq.ProtoReflect.Descriptor instead.
func (*UpdateReportedReq) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateReportedReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpdateReportedReq) GetReported() []byte {
	if x != nil {
		return x.Reported
	}
	return nil
}

func (x *UpdateReportedReq) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// UpdateShadowResp 更新响应, 返回更新后的版本号
type UpdateShadowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备ID
	Version  uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                  // 更新后的版本号
	Success  bool   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`                  // 是否更新成功(版本冲突时为 false)
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                   // 失败原因
}

func (x *UpdateShadowResp) Reset() {
	*x = UpdateShadowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateShadowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateShadowResp) ProtoMessage() {}

func (x *UpdateShadowResp) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateShadowResp.ProtoReflect.Descriptor instead.
func (*UpdateShadowResp) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateShadowResp) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UpdateShadowResp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *UpdateShadowResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateShadowResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// EnsureShadowReq 确保影子存在请求
type EnsureShadowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备ID
}

func (x *EnsureShadowReq) Reset() {
	*x = EnsureShadowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureShadowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureShadowReq) ProtoMessage() {}

func (x *EnsureShadowReq) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureShadowReq.ProtoReflect.Descriptor instead.
func (*EnsureShadowReq) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{7}
}

func (x *EnsureShadowReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// EnsureShadowResp 确保影子存在响应
type EnsureShadowResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备ID
	Version  uint32 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`                  // 当前版本号
	Created  bool   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`                  // 本次是否新建(false=已存在, 幂等返回)
}

func (x *EnsureShadowResp) Reset() {
	*x = EnsureShadowResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shadow_shadow_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnsureShadowResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureShadowResp) ProtoMessage() {}

func (x *EnsureShadowResp) ProtoReflect() protoreflect.Message {
	mi := &file_shadow_shadow_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureShadowResp.ProtoReflect.Descriptor instead.
func (*EnsureShadowResp) Descriptor() ([]byte, []int) {
	return file_shadow_shadow_proto_rawDescGZIP(), []int{8}
}

func (x *EnsureShadowResp) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *EnsureShadowResp) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *EnsureShadowResp) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_shadow_shadow_proto protoreflect.FileDescriptor

var file_shadow_shadow_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2f, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x22, 0x1d, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x69, 0x6e, 0x67, 0x22, 0x1e, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x22, 0x2b, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x7c, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x69, 0x72,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65,
	0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x63, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x69,
	0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x64, 0x65, 0x73, 0x69, 0x72,
	0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x66, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x7d, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68,
	0x61, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x0f, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x53, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x10, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x53, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x32, 0xbc, 0x02, 0x0a, 0x06, 0x53, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x12, 0x29, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x0f, 0x2e, 0x73, 0x68,
	0x61, 0x64, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x73,
	0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38,
	0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x12, 0x14, 0x2e, 0x73, 0x68,
	0x61, 0x64, 0x6f, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x61, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x12, 0x18, 0x2e, 0x73, 0x68, 0x61, 0x64,
	0x6f, 0x77, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x12, 0x45, 0x0a,
	0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x12,
	0x19, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x73, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0c, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x53, 0x68,
	0x61, 0x64, 0x6f, 0x77, 0x12, 0x17, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x45, 0x6e,
	0x73, 0x75, 0x72, 0x65, 0x53, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x2e, 0x45, 0x6e, 0x73, 0x75, 0x72, 0x65, 0x53, 0x68, 0x61,
	0x64, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x42, 0x1d, 0x5a, 0x1b, 0x6f, 0x6e, 0x65, 0x70, 0x61,
	0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x3b,
	0x73, 0x68, 0x61, 0x64, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shadow_shadow_proto_rawDescOnce sync.Once
	file_shadow_shadow_proto_rawDescData = file_shadow_shadow_proto_rawDesc
)

func file_shadow_shadow_proto_rawDescGZIP() []byte {
	file_shadow_shadow_proto_rawDescOnce.Do(func() {
		file_shadow_shadow_proto_rawDescData = protoimpl.X.CompressGZIP(file_shadow_shadow_proto_rawDescData)
	})
	return file_shadow_shadow_proto_rawDescData
}

var file_shadow_shadow_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shadow_shadow_proto_goTypes = []any{
	(*Request)(nil),           // 0: shadow.Request
	(*Response)(nil),          // 1: shadow.Response
	(*GetShadowReq)(nil),      // 2: shadow.GetShadowReq
	(*GetShadowResp)(nil),     // 3: shadow.GetShadowResp
	(*UpdateDesiredReq)(nil),  // 4: shadow.UpdateDesiredReq
	(*UpdateReportedReq)(nil), // 5: shadow.UpdateReportedReq
	(*UpdateShadowResp)(nil),  // 6: shadow.UpdateShadowResp
	(*EnsureShadowReq)(nil),   // 7: shadow.EnsureShadowReq
	(*EnsureShadowResp)(nil),  // 8: shadow.EnsureShadowResp
}
var file_shadow_shadow_proto_depIdxs = []int32{
	0, // 0: shadow.Shadow.Ping:input_type -> shadow.Request
	2, // 1: shadow.Shadow.GetShadow:input_type -> shadow.GetShadowReq
	4, // 2: shadow.Shadow.UpdateDesired:input_type -> shadow.UpdateDesiredReq
	5, // 3: shadow.Shadow.UpdateReported:input_type -> shadow.UpdateReportedReq
	7, // 4: shadow.Shadow.EnsureShadow:input_type -> shadow.EnsureShadowReq
	1, // 5: shadow.Shadow.Ping:output_type -> shadow.Response
	3, // 6: shadow.Shadow.GetShadow:output_type -> shadow.GetShadowResp
	6, // 7: shadow.Shadow.UpdateDesired:output_type -> shadow.UpdateShadowResp
	6, // 8: shadow.Shadow.UpdateReported:output_type -> shadow.UpdateShadowResp
	8, // 9: shadow.Shadow.EnsureShadow:output_type -> shadow.EnsureShadowResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shadow_shadow_proto_init() }
func file_shadow_shadow_proto_init() {
	if File_shadow_shadow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shadow_shadow_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_shadow_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_shadow_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetShadowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_shadow_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetShadowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_shadow_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDesiredReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_shadow_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateReportedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_shadow_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateShadowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_shadow_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*EnsureShadowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shadow_shadow_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*EnsureShadowResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shadow_shadow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shadow_shadow_proto_goTypes,
		DependencyIndexes: file_shadow_shadow_proto_depIdxs,
		MessageInfos:      file_shadow_shadow_proto_msgTypes,
	}.Build()
	File_shadow_shadow_proto = out.File
	file_shadow_shadow_proto_rawDesc = nil
	file_shadow_shadow_proto_goTypes = nil
	file_shadow_shadow_proto_depIdxs = nil
}
