// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: shadow/shadow.proto

package shadow

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Shadow_Ping_FullMethodName = "/shadow.Shadow/Ping"
)

// ShadowClient is the client API for Shadow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShadowClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type shadowClient struct {
	cc grpc.ClientConnInterface
}

func NewShadowClient(cc grpc.ClientConnInterface) ShadowClient {
	return &shadowClient{cc}
}

func (c *shadowClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Shadow_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShadowServer is the server API for Shadow service.
// All implementations must embed UnimplementedShadowServer
// for forward compatibility
type ShadowServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedShadowServer()
}

// UnimplementedShadowServer must be embedded to have forward compatible implementations.
type UnimplementedShadowServer struct {
}

func (UnimplementedShadowServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedShadowServer) mustEmbedUnimplementedShadowServer() {}

// UnsafeShadowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShadowServer will
// result in compilation errors.
type UnsafeShadowServer interface {
	mustEmbedUnimplementedShadowServer()
}

func RegisterShadowServer(s grpc.ServiceRegistrar, srv ShadowServer) {
	s.RegisterService(&Shadow_ServiceDesc, srv)
}

func _Shadow_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShadowServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Shadow_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShadowServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Shadow_ServiceDesc is the grpc.ServiceDesc for Shadow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Shadow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shadow.Shadow",
	HandlerType: (*ShadowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Shadow_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shadow/shadow.proto",
}
