// Code generated by goctl. DO NOT EDIT.
package types

type UserInfo struct {
	Id        uint64 `json:"id"`
	Username  string `json:"username"`
	Nickname  string `json:"nickname"`
	Status    int8   `json:"status"`
	CreatedAt string `json:"created_at"`
}

type UserListResp struct {
	List  []UserInfo `json:"list"`
	Total int64      `json:"total"`
}

type CreateUserReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
	Status   int8   `json:"status"`
	RoleId   uint64 `json:"role_id"`
}

type CreateUserResp struct {
	Id uint64 `json:"id"`
}

type UpdateUserReq struct {
	Id       uint64 `json:"id"`
	Nickname string `json:"nickname"`
	Status   int8   `json:"status"`
}

type UserDeleteReq struct {
	Id uint64 `path:"id"`
}

type UserDetailReq struct {
	Id uint64 `path:"id"`
}

type UserListReq struct {
}

type RoleInfo struct {
	Id       uint64 `json:"id"`
	RoleKey  string `json:"role_key"`
	RoleName string `json:"role_name"`
	Remark   string `json:"remark"`
}

type CreateRoleReq struct {
	RoleKey  string `json:"role_key"`
	RoleName string `json:"role_name"`
	Remark   string `json:"remark"`
}

type CreateRoleResp struct {
	Id uint64 `json:"id"`
}

type RoleListReq struct {
}

type RoleListResp struct {
	List  []RoleInfo `json:"list"`
	Total int64      `json:"total"`
}

type AssignRoleReq struct {
	UserId uint64 `json:"user_id"`
	RoleId uint64 `json:"role_id"`
}

type MenuInfo struct {
	Id         uint64 `json:"id"`
	ParentId   uint64 `json:"parent_id"`
	MenuKey    string `json:"menu_key"`
	MenuName   string `json:"menu_name"`
	Permission string `json:"permission"`
	Path       string `json:"path"`
	Sort       int    `json:"sort"`
}

type CreateMenuReq struct {
	ParentId   uint64 `json:"parent_id"`
	MenuKey    string `json:"menu_key"`
	MenuName   string `json:"menu_name"`
	Permission string `json:"permission"`
	Path       string `json:"path"`
	Sort       int    `json:"sort"`
}

type CreateMenuResp struct {
	Id uint64 `json:"id"`
}

type AssignMenuReq struct {
	RoleId uint64 `json:"role_id"`
	MenuId uint64 `json:"menu_id"`
}

type CheckPermissionReq struct {
	UserId     uint64 `json:"user_id"`
	Permission string `json:"permission"`
}

type CheckPermissionResp struct {
	Allowed bool `json:"allowed"`
}
