// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.4
// source: device/device.proto

package devicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	common "onepark/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetDeviceStatReq 设备统计查询条件
type GetDeviceStatReq struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProductKey string                 `protobuf:"bytes,1,opt,name=product_key,json=productKey,proto3" json:"product_key,omitempty"` // 产品Key, 空表示全部产品
	// 设备类型(1地磁 2门禁 3摄像头...), 0 表示全部类型.
	// 注意: device 表当前没有 type 列, 传非 0 会返回 InvalidArgument,
	// 待 device 表补 type 列后再启用该过滤(与 GetDeviceResp.type 的 TODO 同批).
	Type          int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatReq) Reset() {
	*x = GetDeviceStatReq{}
	mi := &file_device_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatReq) ProtoMessage() {}

func (x *GetDeviceStatReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatReq.ProtoReflect.Descriptor instead.
func (*GetDeviceStatReq) Descriptor() ([]byte, []int) {
	return file_device_device_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeviceStatReq) GetProductKey() string {
	if x != nil {
		return x.ProductKey
	}
	return ""
}

func (x *GetDeviceStatReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

// GetDeviceStatResp 设备数量统计
// 四个字段的关系恒为: total = online + offline + fault
// (device.status 有三个取值, 若只返回 online/offline, 故障设备两边都不计入, total 会对不上)
type GetDeviceStatResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`     // 设备总台数(未删除)
	Online        int64                  `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`   // status = 1 在线
	Offline       int64                  `protobuf:"varint,3,opt,name=offline,proto3" json:"offline,omitempty"` // status = 0 离线/未激活
	Fault         int64                  `protobuf:"varint,4,opt,name=fault,proto3" json:"fault,omitempty"`     // status = 2 故障
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatResp) Reset() {
	*x = GetDeviceStatResp{}
	mi := &file_device_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatResp) ProtoMessage() {}

func (x *GetDeviceStatResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatResp.ProtoReflect.Descriptor instead.
func (*GetDeviceStatResp) Descriptor() ([]byte, []int) {
	return file_device_device_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeviceStatResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetDeviceStatResp) GetOnline() int64 {
	if x != nil {
		return x.Online
	}
	return 0
}

func (x *GetDeviceStatResp) GetOffline() int64 {
	if x != nil {
		return x.Offline
	}
	return 0
}

func (x *GetDeviceStatResp) GetFault() int64 {
	if x != nil {
		return x.Fault
	}
	return 0
}

// GetDeviceReq 设备查询请求
type GetDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备ID(地磁/门禁)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceReq) Reset() {
	*x = GetDeviceReq{}
	mi := &file_device_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceReq) ProtoMessage() {}

func (x *GetDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_device_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceReq.ProtoReflect.Descriptor instead.
func (*GetDeviceReq) Descriptor() ([]byte, []int) {
	return file_device_device_proto_rawDescGZIP(), []int{2}
}

func (x *GetDeviceReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// GetDeviceResp 设备详情响应
type GetDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`  // 设备ID
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                         // 设备类型: 1地磁 2门禁 3摄像头 ...
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                      // 设备状态: online/offline/fault
	Latitude      float64                `protobuf:"fixed64,4,opt,name=latitude,proto3" json:"latitude,omitempty"`                // 纬度
	Longitude     float64                `protobuf:"fixed64,5,opt,name=longitude,proto3" json:"longitude,omitempty"`              // 经度
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // 最近上报时间(秒级时间戳)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResp) Reset() {
	*x = GetDeviceResp{}
	mi := &file_device_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResp) ProtoMessage() {}

func (x *GetDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_device_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResp.ProtoReflect.Descriptor instead.
func (*GetDeviceResp) Descriptor() ([]byte, []int) {
	return file_device_device_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceResp) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetDeviceResp) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GetDeviceResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetDeviceResp) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetDeviceResp) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetDeviceResp) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

var File_device_device_proto protoreflect.FileDescriptor

const file_device_device_proto_rawDesc = "" +
	"\n" +
	"\x13device/device.proto\x12\x0eonepark.device\x1a\x13common/common.proto\"G\n" +
	"\x10GetDeviceStatReq\x12\x1f\n" +
	"\vproduct_key\x18\x01 \x01(\tR\n" +
	"productKey\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\"q\n" +
	"\x11GetDeviceStatResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x16\n" +
	"\x06online\x18\x02 \x01(\x03R\x06online\x12\x18\n" +
	"\aoffline\x18\x03 \x01(\x03R\aoffline\x12\x14\n" +
	"\x05fault\x18\x04 \x01(\x03R\x05fault\"+\n" +
	"\fGetDeviceReq\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xaf\x01\n" +
	"\rGetDeviceResp\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x05 \x01(\x01R\tlongitude\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen2\xb2\x02\n" +
	"\rDeviceService\x124\n" +
	"\x04Ping\x12\x15.onepark.common.Empty\x1a\x15.onepark.common.Empty\x12K\n" +
	"\vSendCommand\x12\x1d.onepark.common.DeviceCommand\x1a\x1d.onepark.common.CommandResult\x12H\n" +
	"\tGetDevice\x12\x1c.onepark.device.GetDeviceReq\x1a\x1d.onepark.device.GetDeviceResp\x12T\n" +
	"\rGetDeviceStat\x12 .onepark.device.GetDeviceStatReq\x1a!.onepark.device.GetDeviceStatRespB\x1fZ\x1donepark/proto/device;devicepbb\x06proto3"

var (
	file_device_device_proto_rawDescOnce sync.Once
	file_device_device_proto_rawDescData []byte
)

func file_device_device_proto_rawDescGZIP() []byte {
	file_device_device_proto_rawDescOnce.Do(func() {
		file_device_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_device_proto_rawDesc), len(file_device_device_proto_rawDesc)))
	})
	return file_device_device_proto_rawDescData
}

var file_device_device_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_device_device_proto_goTypes = []any{
	(*GetDeviceStatReq)(nil),     // 0: onepark.device.GetDeviceStatReq
	(*GetDeviceStatResp)(nil),    // 1: onepark.device.GetDeviceStatResp
	(*GetDeviceReq)(nil),         // 2: onepark.device.GetDeviceReq
	(*GetDeviceResp)(nil),        // 3: onepark.device.GetDeviceResp
	(*common.Empty)(nil),         // 4: onepark.common.Empty
	(*common.DeviceCommand)(nil), // 5: onepark.common.DeviceCommand
	(*common.CommandResult)(nil), // 6: onepark.common.CommandResult
}
var file_device_device_proto_depIdxs = []int32{
	4, // 0: onepark.device.DeviceService.Ping:input_type -> onepark.common.Empty
	5, // 1: onepark.device.DeviceService.SendCommand:input_type -> onepark.common.DeviceCommand
	2, // 2: onepark.device.DeviceService.GetDevice:input_type -> onepark.device.GetDeviceReq
	0, // 3: onepark.device.DeviceService.GetDeviceStat:input_type -> onepark.device.GetDeviceStatReq
	4, // 4: onepark.device.DeviceService.Ping:output_type -> onepark.common.Empty
	6, // 5: onepark.device.DeviceService.SendCommand:output_type -> onepark.common.CommandResult
	3, // 6: onepark.device.DeviceService.GetDevice:output_type -> onepark.device.GetDeviceResp
	1, // 7: onepark.device.DeviceService.GetDeviceStat:output_type -> onepark.device.GetDeviceStatResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_device_device_proto_init() }
func file_device_device_proto_init() {
	if File_device_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_device_proto_rawDesc), len(file_device_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_device_device_proto_goTypes,
		DependencyIndexes: file_device_device_proto_depIdxs,
		MessageInfos:      file_device_device_proto_msgTypes,
	}.Build()
	File_device_device_proto = out.File
	file_device_device_proto_goTypes = nil
	file_device_device_proto_depIdxs = nil
}
