// Code generated by goctl. DO NOT EDIT.
package types

type BillDetailItem struct {
	Name   string  `json:"name"`
	Usage  float64 `json:"usage"`  // 这一档/这个时段用了多少度
	Price  float64 `json:"price"`  // 单价
	Amount float64 `json:"amount"` // 这一档/这个时段多少钱
}

type BillGenerateRequest struct {
	ZoneId string `json:"zoneId"`
	Period string `json:"period"`          // 账期, 如 2026-09; 不传默认本月
	RuleId int64  `json:"ruleId,optional"` // 指定规则; 不传就自动找该区域(或全园区)启用的规则
}

type BillGenerateResponse struct {
	BillNo      string           `json:"billNo"`
	ZoneId      string           `json:"zoneId"`
	PeriodStart string           `json:"periodStart"`
	PeriodEnd   string           `json:"periodEnd"`
	RuleId      int64            `json:"ruleId"`
	RuleName    string           `json:"ruleName"`
	UsageKwh    float64          `json:"usageKwh"`
	Amount      float64          `json:"amount"`
	Detail      []BillDetailItem `json:"detail"`
}

type BillItem struct {
	BillNo      string  `json:"billNo"`
	ZoneId      string  `json:"zoneId"`
	RuleId      int64   `json:"ruleId"`
	PeriodStart string  `json:"periodStart"`
	PeriodEnd   string  `json:"periodEnd"`
	UsageKwh    float64 `json:"usageKwh"`
	Amount      float64 `json:"amount"`
	Status      int64   `json:"status"`
	CreatedAt   string  `json:"createdAt"`
}

type BillListRequest struct {
	ZoneId   string `form:"zoneId,optional"`
	Status   string `form:"status,optional"`   // 1待缴 2已缴 3作废
	Page     int64  `form:"page,optional"`     // 从 1 开始, 默认 1
	PageSize int64  `form:"pageSize,optional"` // 默认 10
}

type BillListResponse struct {
	Total    int64      `json:"total"`
	Page     int64      `json:"page"`
	PageSize int64      `json:"pageSize"`
	List     []BillItem `json:"list"`
}

type PeriodItem struct {
	Name  string  `json:"name"`
	From  string  `json:"from"`
	To    string  `json:"to"`
	Price float64 `json:"price"`
}

type RuleConfig struct {
	Price   float64      `json:"price,optional"`   // ruleType=1 的电价(元/度)
	Base    float64      `json:"base,optional"`    // ruleType=3 的平段电价(没被 periods 覆盖的小时按它算)
	Tiers   []TierItem   `json:"tiers,optional"`   // ruleType=2 的阶梯档位
	Periods []PeriodItem `json:"periods,optional"` // ruleType=3 的峰谷时段
}

type RuleCreateRequest struct {
	Name     string `json:"name"`
	ZoneId   string `json:"zoneId,optional"` // 不传表示全园区默认规则
	RuleType int64  `json:"ruleType"`        // 1单一 2阶梯 3峰谷
	Config   struct {
		Price   float64      `json:"price,optional"`   // ruleType=1 的电价(元/度)
		Base    float64      `json:"base,optional"`    // ruleType=3 的平段电价(没被 periods 覆盖的小时按它算)
		Tiers   []TierItem   `json:"tiers,optional"`   // ruleType=2 的阶梯档位
		Periods []PeriodItem `json:"periods,optional"` // ruleType=3 的峰谷时段
	} `json:"config"`
}

type RuleCreateResponse struct {
	Id int64 `json:"id"`
}

type RuleItem struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	ZoneId   string `json:"zoneId"`
	RuleType int64  `json:"ruleType"`
	Config   struct {
		Price   float64      `json:"price,optional"`   // ruleType=1 的电价(元/度)
		Base    float64      `json:"base,optional"`    // ruleType=3 的平段电价(没被 periods 覆盖的小时按它算)
		Tiers   []TierItem   `json:"tiers,optional"`   // ruleType=2 的阶梯档位
		Periods []PeriodItem `json:"periods,optional"` // ruleType=3 的峰谷时段
	} `json:"config"`
	Status    int64  `json:"status"`
	CreatedAt string `json:"createdAt"`
}

type RuleListRequest struct {
	ZoneId string `form:"zoneId,optional"`
	Status string `form:"status,optional"` // 1启用 0停用, 不传查全部
}

type RuleListResponse struct {
	Total int64      `json:"total"`
	List  []RuleItem `json:"list"`
}

type TierItem struct {
	// optional 不能去掉: 最后一档不封顶时前端传的是 null, 去掉会被参数校验当成缺失而拒绝
	UpTo  *float64 `json:"upTo,optional"`
	Price float64  `json:"price"`
}
