// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AlarmCard struct {
	Total    int64 `json:"total"`    // 活跃告警总数
	Critical int64 `json:"critical"` // level=4 紧急: 需立即响应
	Major    int64 `json:"major"`    // level=3 严重: 需及时处理
	Minor    int64 `json:"minor"`    // level=2 一般: 需关注
	Info     int64 `json:"info"`     // level=1 提示: 一般提示性事件
}

type DeviceCard struct {
	Total   int64 `json:"total"`
	Online  int64 `json:"online"`
	Offline int64 `json:"offline"`
	Fault   int64 `json:"fault"` // status=2 故障
}

type EnergyCard struct {
	TotalKwh   float64  `json:"total_kwh"`   // 当日总用电(度)
	TotalWater *float64 `json:"total_water"` // 当日总用水(吨); M4 契约当前未提供该指标 -> null, 不用 0 冒充
}

type HomeReq struct {
	TenantId int64 `header:"X-Tenant-Id,default=0"`
}

type HomeResp struct {
	WorkOrder WorkOrderCard `json:"work_order"`
	UpdatedAt int64         `json:"updated_at"`
	ElapsedMs int64         `json:"elapsed_ms"`
}

type OverviewReq struct {
	TenantId int64 `header:"X-Tenant-Id,default=0"`
}

type OverviewResp struct {
	WorkOrder *WorkOrderCard `json:"work_order"`
	Alarm     *AlarmCard     `json:"alarm"`
	Device    *DeviceCard    `json:"device"`
	Energy    *EnergyCard    `json:"energy"`
	Degraded  []string       `json:"degraded"` // 降级的数据源标识列表
	Cached    bool           `json:"cached"`   // 是否命中 Redis 缓存
	UpdatedAt int64          `json:"updated_at"`
	ElapsedMs int64          `json:"elapsed_ms"`
}

type WorkOrderCard struct {
	Available    bool     `json:"available"`      // 该路数据是否可用(false = 降级)
	TodayTotal   int64    `json:"today_total"`    // 今日新增工单数
	Unfinished   int64    `json:"unfinished"`     // 未完成(待派单 + 处理中)
	AvgHandleSec *float64 `json:"avg_handle_sec"` // 平均处理时长(秒); M2 契约未暴露 finished_at 时为 null
	CompleteRate float64  `json:"complete_rate"`  // 完成率, 取值 0~1
}
