// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type AlarmCard struct {
	Total    int64 `json:"total"`
	Critical int64 `json:"critical"`
	Major    int64 `json:"major"`
	Minor    int64 `json:"minor"`
}

type DeviceCard struct {
	Total   int64 `json:"total"`
	Online  int64 `json:"online"`
	Offline int64 `json:"offline"`
}

type EnergyCard struct {
	TotalKwh   float64 `json:"total_kwh"`
	TotalWater float64 `json:"total_water"`
}

type HomeReq struct {
	TenantId int64 `header:"X-Tenant-Id,default=0"`
}

type HomeResp struct {
	WorkOrder WorkOrderCard `json:"work_order"`
	UpdatedAt int64         `json:"updated_at"`
	ElapsedMs int64         `json:"elapsed_ms"`
}

type OverviewReq struct {
	TenantId int64 `header:"X-Tenant-Id,default=0"`
}

type OverviewResp struct {
	WorkOrder *WorkOrderCard `json:"work_order"`
	Alarm     *AlarmCard     `json:"alarm"`
	Device    *DeviceCard    `json:"device"`
	Energy    *EnergyCard    `json:"energy"`
	Degraded  []string       `json:"degraded"` // 降级的数据源标识列表
	Cached    bool           `json:"cached"`   // 是否命中 Redis 缓存
	UpdatedAt int64          `json:"updated_at"`
	ElapsedMs int64          `json:"elapsed_ms"`
}

type WorkOrderCard struct {
	Available    bool     `json:"available"`      // 该路数据是否可用(false = 降级)
	TodayTotal   int64    `json:"today_total"`    // 今日新增工单数
	Unfinished   int64    `json:"unfinished"`     // 未完成(待派单 + 处理中)
	AvgHandleSec *float64 `json:"avg_handle_sec"` // 平均处理时长(秒); M2 契约未暴露 finished_at 时为 null
	CompleteRate float64  `json:"complete_rate"`  // 完成率, 取值 0~1
}
