// Code generated by goctl. DO NOT EDIT.
package types

type AlarmStat struct {
	ActiveCount int64 `json:"active_count"`
}

type DeviceStat struct {
	TotalCount  int64 `json:"total_count"`
	OnlineCount int64 `json:"online_count"`
}

type NoticeStat struct {
	PublishedCount int64 `json:"published_count"`
}

type OverviewResp struct {
	TenantId        int64          `json:"tenant_id"`
	WorkOrder       *WorkOrderStat `json:"work_order,omitempty"`
	FallbackMarkers []string       `json:"fallback_markers,omitempty"`
	Cached          bool           `json:"cached"`
}

type ParkingStat struct {
	OccupiedSpaces int64 `json:"occupied_spaces"`
}

type QueryResp struct {
	TenantId        int64          `json:"tenant_id"`
	WorkOrder       *WorkOrderStat `json:"work_order,omitempty"`
	Alarm           *AlarmStat     `json:"alarm,omitempty"`
	Device          *DeviceStat    `json:"device,omitempty"`
	Parking         *ParkingStat   `json:"parking,omitempty"`
	Notice          *NoticeStat    `json:"notice,omitempty"`
	FallbackMarkers []string       `json:"fallback_markers,omitempty"`
	Cached          bool           `json:"cached"`
}

type WorkOrderStat struct {
	TenantId          int64   `json:"tenant_id"`
	Total             int64   `json:"total"`
	TodayCount        int64   `json:"today_count"`
	PendingCount      int64   `json:"pending_count"`
	CompletedToday    int64   `json:"completed_today"`
	AvgProcessMinutes float64 `json:"avg_process_minutes"`
	CompletionRate    float64 `json:"completion_rate"`
}
