// Code generated by goctl. DO NOT EDIT.
//
// 本文件声明 notice-service 的全部 HTTP 路由并注册到 go-zero rest.Server.
// 注意: 这里的 Path 是"服务内网直连路径"; 对外统一经根目录 gateway(8080) 以 /api/notice 前缀转发.
package handler

import (
	"net/http"

	"onepark/app/notice-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

// RegisterHandlers 把本服务的 HTTP 路由挂载到 go-zero HTTP 服务器.
// 入参 server: go-zero 服务器实例; serverCtx: 全局依赖(DB/Redis/Kafka 生产者).
func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 发布公告(立即或定时)
				Method:  http.MethodPost,
				Path:    "/api/notice",
				Handler: CreateNoticeHandler(serverCtx),
			},
			{
				// 公告分页列表
				Method:  http.MethodGet,
				Path:    "/api/notices",
				Handler: ListNoticesHandler(serverCtx),
			},
		},
	)
}
