// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.4
// source: user/user.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	common "onepark/proto/common"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserManage_Ping_FullMethodName            = "/onepark.user.UserManage/Ping"
	UserManage_UserCreate_FullMethodName      = "/onepark.user.UserManage/UserCreate"
	UserManage_UserUpdate_FullMethodName      = "/onepark.user.UserManage/UserUpdate"
	UserManage_UserDelete_FullMethodName      = "/onepark.user.UserManage/UserDelete"
	UserManage_UserDetail_FullMethodName      = "/onepark.user.UserManage/UserDetail"
	UserManage_UserList_FullMethodName        = "/onepark.user.UserManage/UserList"
	UserManage_CheckPermission_FullMethodName = "/onepark.user.UserManage/CheckPermission"
)

// UserManageClient is the client API for UserManage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserManageClient interface {
	// Ping 健康检查
	Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error)
	// UserCreate 新建用户(bcrypt 加密密码)
	UserCreate(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
	// UserUpdate 更新用户资料(昵称/状态)
	UserUpdate(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*common.Empty, error)
	// UserDelete 删除用户
	UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*common.Empty, error)
	// UserDetail 查询单用户详情
	UserDetail(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserInfo, error)
	// UserList 分页列出用户
	UserList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*UserListResp, error)
	// CheckPermission 校验用户是否拥有某 permission(用户->角色->菜单权限汇总).
	// 由网关在写操作前统一调用; 以网关注入的已鉴权 user_id 为准(调用方为网关, 可信).
	CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error)
}

type userManageClient struct {
	cc grpc.ClientConnInterface
}

func NewUserManageClient(cc grpc.ClientConnInterface) UserManageClient {
	return &userManageClient{cc}
}

func (c *userManageClient) Ping(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, UserManage_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManageClient) UserCreate(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResp)
	err := c.cc.Invoke(ctx, UserManage_UserCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManageClient) UserUpdate(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, UserManage_UserUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManageClient) UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*common.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.Empty)
	err := c.cc.Invoke(ctx, UserManage_UserDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManageClient) UserDetail(ctx context.Context, in *UserDetailReq, opts ...grpc.CallOption) (*UserInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserInfo)
	err := c.cc.Invoke(ctx, UserManage_UserDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManageClient) UserList(ctx context.Context, in *common.Empty, opts ...grpc.CallOption) (*UserListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserListResp)
	err := c.cc.Invoke(ctx, UserManage_UserList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userManageClient) CheckPermission(ctx context.Context, in *CheckPermissionReq, opts ...grpc.CallOption) (*CheckPermissionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPermissionResp)
	err := c.cc.Invoke(ctx, UserManage_CheckPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserManageServer is the server API for UserManage service.
// All implementations must embed UnimplementedUserManageServer
// for forward compatibility.
type UserManageServer interface {
	// Ping 健康检查
	Ping(context.Context, *common.Empty) (*common.Empty, error)
	// UserCreate 新建用户(bcrypt 加密密码)
	UserCreate(context.Context, *CreateUserReq) (*CreateUserResp, error)
	// UserUpdate 更新用户资料(昵称/状态)
	UserUpdate(context.Context, *UpdateUserReq) (*common.Empty, error)
	// UserDelete 删除用户
	UserDelete(context.Context, *UserDeleteReq) (*common.Empty, error)
	// UserDetail 查询单用户详情
	UserDetail(context.Context, *UserDetailReq) (*UserInfo, error)
	// UserList 分页列出用户
	UserList(context.Context, *common.Empty) (*UserListResp, error)
	// CheckPermission 校验用户是否拥有某 permission(用户->角色->菜单权限汇总).
	// 由网关在写操作前统一调用; 以网关注入的已鉴权 user_id 为准(调用方为网关, 可信).
	CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionResp, error)
	mustEmbedUnimplementedUserManageServer()
}

// UnimplementedUserManageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserManageServer struct{}

func (UnimplementedUserManageServer) Ping(context.Context, *common.Empty) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedUserManageServer) UserCreate(context.Context, *CreateUserReq) (*CreateUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserCreate not implemented")
}
func (UnimplementedUserManageServer) UserUpdate(context.Context, *UpdateUserReq) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UserUpdate not implemented")
}
func (UnimplementedUserManageServer) UserDelete(context.Context, *UserDeleteReq) (*common.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UserDelete not implemented")
}
func (UnimplementedUserManageServer) UserDetail(context.Context, *UserDetailReq) (*UserInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method UserDetail not implemented")
}
func (UnimplementedUserManageServer) UserList(context.Context, *common.Empty) (*UserListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UserList not implemented")
}
func (UnimplementedUserManageServer) CheckPermission(context.Context, *CheckPermissionReq) (*CheckPermissionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPermission not implemented")
}
func (UnimplementedUserManageServer) mustEmbedUnimplementedUserManageServer() {}
func (UnimplementedUserManageServer) testEmbeddedByValue()                    {}

// UnsafeUserManageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserManageServer will
// result in compilation errors.
type UnsafeUserManageServer interface {
	mustEmbedUnimplementedUserManageServer()
}

func RegisterUserManageServer(s grpc.ServiceRegistrar, srv UserManageServer) {
	// If the following call panics, it indicates UnimplementedUserManageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserManage_ServiceDesc, srv)
}

func _UserManage_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManageServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManage_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManageServer).Ping(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManage_UserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManageServer).UserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManage_UserCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManageServer).UserCreate(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManage_UserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManageServer).UserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManage_UserUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManageServer).UserUpdate(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManage_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManageServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManage_UserDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManageServer).UserDelete(ctx, req.(*UserDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManage_UserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManageServer).UserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManage_UserDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManageServer).UserDetail(ctx, req.(*UserDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManage_UserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManageServer).UserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManage_UserList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManageServer).UserList(ctx, req.(*common.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserManage_CheckPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPermissionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserManageServer).CheckPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserManage_CheckPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserManageServer).CheckPermission(ctx, req.(*CheckPermissionReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserManage_ServiceDesc is the grpc.ServiceDesc for UserManage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserManage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "onepark.user.UserManage",
	HandlerType: (*UserManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _UserManage_Ping_Handler,
		},
		{
			MethodName: "UserCreate",
			Handler:    _UserManage_UserCreate_Handler,
		},
		{
			MethodName: "UserUpdate",
			Handler:    _UserManage_UserUpdate_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _UserManage_UserDelete_Handler,
		},
		{
			MethodName: "UserDetail",
			Handler:    _UserManage_UserDetail_Handler,
		},
		{
			MethodName: "UserList",
			Handler:    _UserManage_UserList_Handler,
		},
		{
			MethodName: "CheckPermission",
			Handler:    _UserManage_CheckPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
